FORMAT: 1A
HOST: https://app.expan.do/api/v2

# Expando Public API (v2.100)

API documentation for app.expan.do

**Note**: The `Authorization` header has to include `Bearer` keyword.
*Example:* If your token is `5Lw1cA`, the whole `Authorization` header
will be `Bearer 5Lw1cA`.

Also note that you can consider the response successful
**only if the HTTP response status code is in `20x` range**.

# Release notes
- v2.100 - Extended `packages` field in `/fulfillment` endpoint to support Amazon marketplace with detailed tracking
- v2.99 - Changed `carrier` enum values in the `/fulfillment` endpoint. See the enum definition for all changes.
- v2.98 - Added `packages` field to `/fulfillment` endpoint, optional for Alza marketplace
- v2.97 - Added `taxRatePercentDecimal` field to `/orders` and `/orderfeed` and deprecated `taxRatePercent` field
- v2.96 - Added `buyerCustomInfo` field to `/orders` and `/orderfeed`
- v2.95 - Added `GuaranteeClaim` event type and `additionalItems` field to `/finances/orderevents`
- v2.94 - Added `parcelShop` field to `/orderfeed`
- v2.93 - Added Amazon carrier code `DHL eCommerce`
- v2.92 - Deprecated glami_cz marketplace
- v2.91 - Added kaufland_at, kaufland_pl, allegro_cz, allegro_pl, allegro_sk, limetka_cz, limetka_gr, limetka_sk, baskedo_bg, baskedo_hu, bol_nl, ebay_at, ebay_cz, ebay_fr, ebay_pl, ebay_de, ebay_us and ebay_uk marketplaces`
- v2.90 - Added `Chargeback` event type to `/finances/orderevents`
- v2.89 - Added Amazon carrier code (WEDOLOGISTICS)
- v2.88 - Added Kafuland carrier code (WEDOLOGISTICS) 
- v2.87 - Added `marketplaceOrderIds` query parameter to `/orders` endpoint
- v2.86 - Added transaction type and date to invoices on order
- v2.85 - Added CZPOSTP Post office delivery for shipping carrier code CZPOST (Parcel shop identification for Alza)
- v2.84 - Added Amazon carrier code (CTTExpress)
- v2.83 - Added Return labels (`/return-labels`, `/orders`, `/orderfeed`)
- v2.82 - Added Kaufland carrier code (SPS - Slovak Parcel Service)
- v2.81 - Added Geis to supported carriers for Kaufland
- v2.80 - Added fullNumber to Fulfillment
- v2.72 - Changed Kaufland carrier PACKETA to Packeta
- v2.71 - Added Kaufland carrier code (CZECHPOST)
- v2.70 - Added parameter (shipMethod) to `POST /fulfillment`
- v2.69 - Added Kaufland carrier code (PACKETA)
- v2.68 - Added new Alza carrier code (DPDALZABOX, DPDBOX, DPDPARCELSHOP)
- v2.67 - Deprecated real_de marketplace, add kaufland_de, kaufland_cz and kaufland_sk marketplaces

## Orders [/orders{?fromLastChanged}]

### List Orders [GET]
Returns up to 100 orders by last change date.

You can paginate naturally through orders by taking `lastChanged` attribute
of the last order on a page and making the request again with this new value in your query.

You will get an empty array once you exhaust order changes. Some pages may contain less than 100 orders, but this does not mean it is the last page.

You can also request specific orders by providing `marketplaceOrderIds` parameter in the query.
It is a comma separated list of marketplace order IDs and may contain up to 100 IDs.

Parameters `fromLastChanged` and `marketplaceOrderIds` cannot be used simultaneously.

+ Parameters
    + fromLastChanged - string - ISO date
    + marketplaceOrderIds - string - comma separated list of marketplace order IDs

+ Request

    + Headers

            Authorization: Bearer <token>


+ Response 200 (application/json)
    + Attributes ( array[ Order ] )

## Order Feed [/orderfeed{?access_token}{?days}]

### Get Order Feed [GET]
Returns feed which is an old version of getting orders with new parameters.

**Explanation of attributes:**

`fulfillmentChannel`:
- `Seller` - fulfilled by seller
- `MediatedCarrier` - fulfilled by a marketplace (currently used with Alza and Mall)
- `FBA` - Fulfilled by Amazon

`businessOrder` - B2B or B2C order type
`isPrime` - only for Amazon
`isComplete` - received all the information for order
`isRefunded` - is the order refunded or not
`customer` - information about the customer includes only delivery address


+ Parameters
    + access_token ( string ) - API Bearer token
    + days ( number ) - number of days to lookback


+ Response 200 (text/xml)
    + Body
        <?xml version="1.0" encoding='UTF-8'?>
        <orders>
        <order>
            <orderId>000-0000000-0000000</orderId>
            <orderStatus>Shipped</orderStatus>
            <purchaseDate>2019-01-06 21:00:45</purchaseDate>
            <marketplace>AMAZON UK</marketplace>
            <venue>AMAZON</venue>
            <fulfillmentChannel>Seller</fulfillmentChannel>
            <businessOrder>false</businessOrder>
            <totalPrice>18.13</totalPrice>
            <totalItemTax>0</totalItemTax>
            <currencyCode>GBP</currencyCode>
            <language>UK</language>
            <paymentMethod>Other</paymentMethod>
            <shippingMethod>Std UK Dom_3</shippingMethod>
            <shipServiceLevel>B2C</shipServiceLevel>
            <deliveryBranchId></deliveryBranchId>
            <shippingPrice>3</shippingPrice>
            <latestShipDate>2019-01-08 21:00:45</latestShipDate>
            <latestDeliveryDate>2019-01-15 21:00:45</latestDeliveryDate>
            <isPremiumOrder>false</isPremiumOrder>
            <isPrime>false</isPrime>
            <isComplete>false</isComplete>
            <isRefunded>false</isRefunded>
            <invoiceUrls>
                <url>https://www.Amazon.fr/gp/invoice/download.html?v=urn%3aalx%3aver%3a01dcc42c-0000-000a-aaa0-00000a000aa0&t=EU_Retail_Forward</url>
            </invoiceUrls>
            <invoices>
                <invoice>
                    <id>INV-FR-000000000-2019-00</id>
                    <type>SHIPMENT</type>
                    <url>https://www.Amazon.fr/gp/invoice/download.html?v=urn%3aalx%3aver%3a01dcc42c-0000-000a-aaa0-00000a000aa0&t=EU_Retail_Forward</url>
                    <date>2019-01-06 21:00:45</date>
                </invoice>
            </invoices>
            <customer>
                <companyName>John Don & Co, Inc</companyName>
                <firstname>john</firstname>
                <surname>dow</surname>
                <email>xxxxxxxxxxxxxxx@marketplace.amazon.co.uk</email>
                <phone></phone>
                <taxId></taxId>
                <taxCountry></taxCountry>
                <address>
                    <address1>school house nursery , school lane, holmpton,</address1>
                    <address2></address2>
                    <address3></address3>
                    <city>hull</city>
                    <zip>123456</zip>
                    <stateOrRegion>east yorkshire</stateOrRegion>
                    <country>GB</country>
                </address>
            </customer>
            <items>
                <item>
                    <itemId>12345</itemId>
                    <externalId></externalId>
                    <itemPrice>15.13</itemPrice>
                    <itemQuantity>1</itemQuantity>
                    <itemName>Philips Disney Frozen Lampshade</itemName>
                    <orderItemId>00000000000000</orderItemId>
                    <itemTax>0</itemTax>
                    <shippingDiscount>0</shippingDiscount>
                    <shippingDiscountTax>0</shippingDiscountTax>
                    <promotionDiscount>0</promotionDiscount>
                    <promotionDiscountTax>0</promotionDiscountTax>
                    <shippingPrice>3</shippingPrice>
                    <shippingTax>0</shippingTax>
                    <lineItemPrice>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax>15.13</withTax>
                    </lineItemPrice>
                    <lineItemDiscount>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax></withTax>
                    </lineItemDiscount>
                    <deliveryPrice>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax>3</withTax>
                    </deliveryPrice>
                    <deliveryDiscount>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax></withTax>
                    </deliveryDiscount>
                    <marketplaceCommission>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax></withTax>
                    </marketplaceCommission>
                    <buyerCustomInfo>
                        <info>
                            <name>CustomizedURL</name>
                            <value><![CDATA[https://zme-caps.amazon.com/t/xxxxxxxxxxxx/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/00]]></value>
                        </info>
                        <info>
                            <name>GiftMessageText</name>
                            <value><![CDATA[Example Text]]></value>
                        </info>
                    </buyerCustomInfo>
                </item>
            </items>
            <price>
                <delivery>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax>3</withTax>
                </delivery>
                <items>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax>15.23</withTax>
                </items>
                <payment>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax></withTax>
                </payment>
                <total>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax>18.23</withTax>
                </total>
                <totalDiscount>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax></withTax>
                </totalDiscount>
            </price>
            <payment>
                <paymentMethod>CashOnDelivery</paymentMethod>
                <cashOnDelivery>
                    <toPay>18.23</toPay>
                    <servicePrice></servicePrice>
                </cashOnDelivery>
            </payment>
            <delivery>
                <shippingCarrier>GEISPARCEL</shippingCarrier>
                <shippingCarrierService>GEIS</shippingCarrierService>
            </delivery>
            <cancelRequest>
                <cancelReason></cancelReason>
                <marketplaceCancelReason></marketplaceCancelReason>
            </cancelRequest>
            <returnLabels>
                <returnLabel>
                    <status>Created</status>
                    <requestCreatedAt>2022-03-02 22:00:00</requestCreatedAt>
                    <shipmentNumber>123456</shipmentNumber>
                    <labelNumber>1</labelNumber>
                    <packageLabelUrls>
                        <url>https://example.com/file_pdf</url>
                    </packageLabelUrls>
                    <errorMessage></errorMessage>
                </returnLabel>
            </returnLabels>
            <parcelShop>
                <parcelShopIdentification>ZASILKOVNA</parcelShopIdentification>
                <parcelShopBranchCode>123</parcelShopBranchCode>
            </parcelShop>
        </order>
        <order>
            <orderId>1223456679</orderId>
            <orderStatus>Canceled</orderStatus>
            <purchaseDate>2021-07-01 12:49:00</purchaseDate>
            <marketplace>ALZA CZ</marketplace>
            <venue>ALZA</venue>
            <fulfillmentChannel>MediatedCarrier</fulfillmentChannel>
            <businessOrder>false</businessOrder>
            <totalPrice>861</totalPrice>
            <totalItemTax>0</totalItemTax>
            <currencyCode>CZK</currencyCode>
            <language>CZ</language>
            <paymentMethod />
            <shippingMethod>B2C</shippingMethod>
            <shipServiceLevel>B2C</shipServiceLevel>
            <deliveryBranchId />
            <shippingPrice>0</shippingPrice>
            <latestShipDate>2021-07-02 13:00:00</latestShipDate>
            <latestDeliveryDate>2021-07-31 12:49:00</latestDeliveryDate>
            <isPremiumOrder>false</isPremiumOrder>
            <isPrime>false</isPrime>
            <isComplete>false</isComplete>
            <isRefunded>false</isRefunded>
            <invoiceUrls />
            <invoices />
            <customer>
                <companyName>-</companyName>
                <firstname>Test</firstname>
                <surname>Test</surname>
                <email>test.test@test.cz</email>
                <phone>+1234560344</phone>
                <taxId />
                <taxCountry />
                <address>
                    <address1>Test 354</address1>
                    <address2 />
                    <address3 />
                    <city>Test</city>
                    <zip>22222</zip>
                    <stateOrRegion />
                    <country>CZ</country>
                </address>
            </customer>
            <items>
                <item>
                    <itemId>12348</itemId>
                    <externalId />
                    <itemPrice>861</itemPrice>
                    <itemQuantity>1</itemQuantity>
                    <itemName>Test</itemName>
                    <orderItemId>1234556</orderItemId>
                    <itemTax>0</itemTax>
                    <shippingDiscount>0</shippingDiscount>
                    <shippingDiscountTax>0</shippingDiscountTax>
                    <promotionDiscount>0</promotionDiscount>
                    <promotionDiscountTax>0</promotionDiscountTax>
                    <shippingPrice>0</shippingPrice>
                    <shippingTax>0</shippingTax>
                    <lineItemPrice>
                        <tax />
                        <taxRatePercent />
                        <taxRatePercentDecimal />
                        <withoutTax>861</withoutTax>
                        <withTax />
                    </lineItemPrice>
                    <lineItemDiscount>
                        <tax />
                        <taxRatePercent />
                        <taxRatePercentDecimal />
                        <withoutTax />
                        <withTax />
                    </lineItemDiscount>
                    <deliveryPrice>
                        <tax />
                        <taxRatePercent />
                        <taxRatePercentDecimal />
                        <withoutTax />
                        <withTax />
                    </deliveryPrice>
                    <deliveryDiscount>
                        <tax />
                        <taxRatePercent />
                        <taxRatePercentDecimal />
                        <withoutTax />
                        <withTax />
                    </deliveryDiscount>
                    <marketplaceCommission>
                        <tax />
                        <taxRatePercent />
                        <taxRatePercentDecimal />
                        <withoutTax />
                        <withTax />
                    </marketplaceCommission>
                    <buyerCustomInfo>
                    </buyerCustomInfo>
                </item>
            </items>
            <price>
                <delivery>
                    <tax />
                    <taxRatePercent />
                    <taxRatePercentDecimal />
                    <withoutTax />
                    <withTax />
                </delivery>
                <items>
                    <tax />
                    <taxRatePercent />
                    <taxRatePercentDecimal />
                    <withoutTax>861</withoutTax>
                    <withTax />
                </items>
                <payment>
                    <tax />
                    <taxRatePercent />
                    <taxRatePercentDecimal />
                    <withoutTax />
                    <withTax />
                </payment>
                <total>
                    <tax />
                    <taxRatePercent />
                    <taxRatePercentDecimal />
                    <withoutTax>861</withoutTax>
                    <withTax />
                </total>
                <totalDiscount>
                    <tax />
                    <taxRatePercent />
                    <taxRatePercentDecimal />
                    <withoutTax />
                    <withTax />
                </totalDiscount>
            </price>
            <payment>
                <paymentMethod>CreditCard</paymentMethod>
                <cashOnDelivery>
                    <toPay />
                    <servicePrice />
                </cashOnDelivery>
            </payment>
            <delivery>
                <shippingCarrier>DPD</shippingCarrier>
                <shippingCarrierService>DPD</shippingCarrierService>
            </delivery>
            <cancelRequest>
                <cancelReason></cancelReason>
                <marketplaceCancelReason></marketplaceCancelReason>
            </cancelRequest>
        </order>
        <order>
            <orderId>ABC12345DEF</orderId>
            <orderStatus>Shipped</orderStatus>
            <purchaseDate>2022-02-22 22:22:22</purchaseDate>
            <marketplace>CDISCOUNT FR</marketplace>
            <venue>CDISCOUNT</venue>
            <fulfillmentChannel>Seller</fulfillmentChannel>
            <businessOrder>false</businessOrder>
            <totalPrice>222.22</totalPrice>
            <totalItemTax>0</totalItemTax>
            <currencyCode>EUR</currencyCode>
            <language>FR</language>
            <paymentMethod>CreditCard</paymentMethod>
            <shippingMethod></shippingMethod>
            <shipServiceLevel></shipServiceLevel>
            <deliveryBranchId></deliveryBranchId>
            <shippingPrice>0</shippingPrice>
            <latestShipDate>2022-03-02 22:00:00</latestShipDate>
            <latestDeliveryDate>2022-03-02 22:00:00</latestDeliveryDate>
            <isPremiumOrder>false</isPremiumOrder>
            <isPrime>false</isPrime>
            <isComplete>false</isComplete>
            <isRefunded>false</isRefunded>
            <invoiceUrls>
        </invoiceUrls>
            <invoices>
        </invoices>
            <customer>
                <companyName>-</companyName>
                <firstname>John</firstname>
                <surname>Doe</surname>
                <email>*************@clemarche.com</email>
                <phone>2222222222</phone>
                <taxId></taxId>
                <taxCountry></taxCountry>
                <address>
                    <address1>Test 354</address1>
                    <address2></address2>
                    <address3></address3>
                    <city>PARIS</city>
                    <zip>22222</zip>
                    <stateOrRegion></stateOrRegion>
                    <country>FR</country>
                </address>
            </customer>
            <items>
                <item>
                    <itemId>22222</itemId>
                    <externalId></externalId>
                    <itemPrice>222.22</itemPrice>
                    <itemQuantity>1</itemQuantity>
                    <itemName>Ink Tank</itemName>
                    <orderItemId>HP222222</orderItemId>
                    <itemTax>0</itemTax>
                    <shippingDiscount>0</shippingDiscount>
                    <shippingDiscountTax>0</shippingDiscountTax>
                    <promotionDiscount>0</promotionDiscount>
                    <promotionDiscountTax>0</promotionDiscountTax>
                    <shippingPrice>0</shippingPrice>
                    <shippingTax>0</shippingTax>
                    <lineItemPrice>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax>222.22</withTax>
                    </lineItemPrice>
                    <lineItemDiscount>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax></withTax>
                    </lineItemDiscount>
                    <deliveryPrice>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax></withTax>
                    </deliveryPrice>
                    <deliveryDiscount>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax></withTax>
                    </deliveryDiscount>
                    <marketplaceCommission>
                        <tax></tax>
                        <taxRatePercent></taxRatePercent>
                        <taxRatePercentDecimal></taxRatePercentDecimal>
                        <withoutTax></withoutTax>
                        <withTax></withTax>
                    </marketplaceCommission>
                    <buyerCustomInfo>
                    </buyerCustomInfo>
                </item>
            </items>
            <price>
                <delivery>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax>0</withTax>
                </delivery>
                <items>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax>222.22</withTax>
                </items>
                <payment>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax></withTax>
                </payment>
                <total>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax>222.22</withTax>
                </total>
                <totalDiscount>
                    <tax></tax>
                    <taxRatePercent></taxRatePercent>
                    <taxRatePercentDecimal></taxRatePercentDecimal>
                    <withoutTax></withoutTax>
                    <withTax></withTax>
                </totalDiscount>
            </price>
            <payment>
                <paymentMethod>CreditCard</paymentMethod>
                <cashOnDelivery>
                    <toPay></toPay>
                    <servicePrice></servicePrice>
                </cashOnDelivery>
            </payment>
            <delivery>
                <shippingCarrier>DPD</shippingCarrier>
                <shippingCarrierService>DPD</shippingCarrierService>
            </delivery>
            <cancelRequest>
                <cancelReason>BuyerCanceled</cancelReason>
                <marketplaceCancelReason>EXAMPLE_REASON</marketplaceCancelReason>
            </cancelRequest>
            <returnLabels>
            </returnLabels>
            <parcelShop>
                <parcelShopIdentification></parcelShopIdentification>
                <parcelShopBranchCode></parcelShopBranchCode>
            </parcelShop>
        </order>
        </orders>

## Package Labels [/package-labels]

### Generate package labels [POST /package-labels]

Request package shipping labels for one; or multiple orders (if you're consolidating multiple orders to a single branch).

By default, a label for a *single package* will be generated. If you wish to split your order/s to multiple packages, you can provide your own `packages` parameter.

Returns 202 while the labels are being generated. Please make subsequent GET calls to a created resource to fetch the current status.

+ Request
    + Attributes (CreateLabelInput)
    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)
    + Attributes (PackageLabelData)

+ Response 202 (application/json)
    + Attributes
        + status: Generating ( string )
        + packageLabelsId: `111-222-aaa` ( string )
        + packages ( array [FulfillmentPackage] )

+ Response 400 (application/json)
    + Attributes
        + message ( enum )
            + Members
                + You can only consolidate orders belonging to the same branch.
                + `Some items(number) are not included in packages.`
                + All orders must be from same marketplace.
                + `Item with id: string doesn't exist in order.`
                + `Packages contains invalid marketplaceOrderId.`
                + `Items quantity doesn't match. Ordered: (number), Provided: (number)`
                + Please check, that every order is eligible for package-labels generation.
                + You have already requested package labels for different marketplaceOrderIds.'
+ Response 404 (application/json)
    + Attributes
        + message ( enum )
            + Members
                + `Can not find resources.`
                + `Some resources were not found.`

### Get package labels [GET /package-labels/{packageLabelsId}]
Fetch package labels.

While the labels are being generated, you'll receive status `Generating` and your request should be retried after few seconds. Once the labels are generated, you'll receive status `Generated` and labels PDF will be available for download.

In case of unexpected issues with the carrier API, you might occasionally receive status `Failed` with details in `failReason` . You might retry the request with revised input.

+ Parameters
    + packageLabelsId: 111abc333 ( string )
+ Request

    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)

    + Headers

            Retry-After: 5

    + Attributes ( PackageLabelData )

+ Response 404 (application/json)
    + Attributes
        + packageLabelsId: 11abc333 ( string )
        + message ( enum )
            + Members
                + Resource not found.
                + `Resource not found, have you requested for creation?`




### Fulfill order/s using package labels data [POST /package-labels/{packageLabelsId}/fulfill]
If you have package shipping labels generated for one or multiple orders, you can fulfill these orders directly using the data provided for shipping labels. This is a shortcut for `Update Fulfillment` action so that you don't need to provide any details
+ Parameters
    + packageLabelsId: 111abc333 ( string )
+ Request
    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)
    + Attributes ( Fulfillment )

+ Response 400 (application/json)
    + Attributes
        + packages ( array[FulfillmentPackage] )
        + packageLabelsId: 123-abc-345 ( string )
        + failReason: Maximum number of required packages exceeded. Actual limit is 1. ( string )


## Fulfillment [/fulfillment]

### Update Fulfillment [POST]

We provide one generic fulfillment endpoint that supports multiple marketplaces.
However note that each platform has its own unique requirements you have
to follow for peaceful communication with the marketplace.

**Generic:**

Attributes `shipDate`, `carrierName`, `fullNumber` and `trackingNumber` are nullable.

If `shipDate` is `null`, then `shipDate` will be set to current UTC time instead.
Subsequent updates of `shipDate` will not overwrite the initial value.

Check individual marketplaces for interpretation of each status.

**For Amazon orders:**

If the `carrier` is `Other`, the `carrierName` must be set. If the `carrier`
is not `Other`, `carrierName` must be `null`.

Any updates for Amazon are currently seen as with status `Shipped` except status `Canceled` which will trigger order cancellation.

For updates with status `Canceled` only can you specify the cancel reason (`cancelReason` parameter).
If `cancelReason` is not specified, the first default value will be fetched from `cancelRequest.cancelReason` on order (only `BuyerCanceled` for now) and if there is no cancel request, then the final default value will be `NoInventory`.

> **NOTE**: `shipDate` time must be between order purchase date time and current time (UTC). Amazon will reject the fulfillment otherwise.

**For Mall orders:**

The workflow and supported statuses are as follow:
- `Registered` - seller starts processing the order
- `Shipped` - seller gives shipment to carrier
  - extra `trackingNumber` and `trackingUrl` fields need to be send in request.
- `Delivered` - seller receives confirmation from carrier about the shipment delivery (`deliveryDate` attribute is filled automatically, with actual date when fulfillment endpoint is called with status `Delivered`)
- `Canceled`
Each status will change Mall order state accordingly except `Registered` which will change state to `Shipping`.

> **NOTE**: First letter of status string is capital

**For Alza orders:**

> **NOTE**: If your Alza Dropshipment contract allows usage of marketplace-provided package shipping labels, you must use `/package-labels/{packageLabelsId}/fulfill` endpoint.

Field `trackingNumber` is always required. Status `Shipped` also
requires additional fields (see specification). Those fields are _not_ required
in other statuses.

- The best choice is to map _order's_ `delivery.shippingCarrier` to `carrierName` and `delivery.shippingCarrierService` to `carrier`
- `carrier` is one of [Alza's delivery types](https://dropa.docs.apiary.io/#/data-structures/0/shipping-carrier-delivery-type). `carrierName` is one of [Alza's carrier codes](https://dropa.docs.apiary.io/#/data-structures/0/shipping-carrier-code)
- If the `carrier` is `Supplier`, the `carrierName` can be empty or one of [Alza's carrier codes](https://dropa.docs.apiary.io/#/data-structures/0/shipping-carrier-code)
- The `packages` field is supported for Alza orders only, allowing to specify shipment details for multiple packages within an order.

The `Registered` status has no effect. Supports all other statuses.

**For eMAG orders:**

Supports `Shipped` status. Other have no effect.

**For Cdiscount orders:**

***Order acceptation:***
Cdiscount orders must be accepted and there are two ways, how to accept Cdiscount order:
- Automatic acceptation by Cdiscount. This means all Cdiscount orders will be automatically accepted. It can be turned on/off at Cdiscount seller portal.
- Manual acceptation. This means all Cdiscount orders must be accepted by seller.

Manual Acceptation:
- All orders in the "Pending" state are not accepted and must be accepted within 48 after order creation.
- There is automatic order acceptation at EXPANDO and EXPANDO will accept each order after 47 hours after its creation.
- If you want to accept order via EXPANDO API, you have to set its fulfilment to state "Registered".
- It is also possible to manually accept order in EXPANDO APP.
- If you want to cancel an order for any reason, you can do that by setting fulfillment status to “Canceled”. Be aware that you must do it within 47 hours after the order was first received.

***Order confirmation:***
- When the order is already in status `Unshipped` you are eligible to confirm that order by setting fulfillment status to `Shipped` state. Be aware that when you are changing fulfillment status to `Shipped` you will have to include tracking details (marketplace, carrier, carrierName, trackingNumber, etc.) in your request.
- If the `carrier` is `Other`, the `carrierName` must be set. If the `carrier` is not `Other`, `carrierName` must be `null`. The workflow and supported statuses are as follow:
   - `Registered` - seller accepts the order
   - `Shipped` - seller gives shipment to carrier
- `Warning: Cdiscount orders in the "Pending" state are not payed yet. A seller should wait for the state "Unshipped" to avoid dispatching unpaid orders.`

***Shipped order confirmation example:***

    {
        "marketplaceOrderId": "1111111111A11A1",
        "marketplace": "cdiscount_fr",
        "status": "Shipped",
        "trackingNumber": "22222222222",
        "trackingUrl": "https://gls-group.eu",
        "carrier": "GLS",
        "carrierName": null,
        "shipDate": "2019-02-28T14:25:00.000Z"
    }

***Cdiscount payment fees:***
- When the order contains special Cdiscount payment fees, total order price does not match sum of order item prices.
- These special fees can be found in payment property of the order.

Order Feed (/orderfeed endpoint):
```xml
<payment>
    <cashOnDelivery>
        <servicePrice>1.23</servicePrice>
    </cashOnDelivery>
</payment>
```

Orders (/orders endpoint):
```json
{
    payment: {
        cashOnDelivery: {
            servicePrice: 1.23
        }
    }
}
```

**For Kaufland orders:**

Both `Registered` and `Shipped` statuses will confirm shipment of the order. You can optionally add shipping info.
If the `carrier` is `Other`, the `carrierName` must be set. If the `carrier` is not `Other`, `carrierName`
must be `null` and `trackingNumber` must be set.

*Note: Kaufland does not allow us to change the trackingNumber once it has been set.*

+ Request (application/json)

    + Headers

            Authorization: Bearer <token>

    + Attributes ( InputFulfillment )

+ Response 200 (application/json)
    + Attributes ( Fulfillment )

## PDF Documents [/branch-barcodes-batch]

### Barcodes for Branch Delivery [POST /branch-barcodes-batch]
Generate a batch of **branch delivery barcodes** in printable PDF format.

Generated barcodes have to be printed and sticked onto the specific items that are being delivered
to a marketplace branch.

You only need to provide a list of `marketplaceOrderIds` for which you wish the barcodes
to be generated in a single PDF.

*Note that you can generate barcodes only for orders that are actually delivered to branch.*

This endpoint has a timeout of 29 seconds. If the document cannot be generated in time, you will
receive an appropriate message (see section _Response 500_ for more details).

+ Request
    + Attributes (BranchBarcodesBatchInput)
    + Headers

            Authorization: Bearer <token>

+ Response 201 (application/json)
    + Attributes (BranchBarcodesBatch)

+ Response 400 (application/json)
    This endpoint specifically responds with `400` if some of the provided orders
    do not contain any delivery barcodes; or orders cannot be found.

    + Attributes
        + message: `No delivery barcodes found for orders with marketplaceOrderIds: 1234, 5678` ( string, required )

+ Response 500 (application/json)
    It is possible for the request to occasionally time out. You will get
    response `500` and you can safely retry your request after the number
    of seconds specified in `Retry-After` header.

    + Headers

            Retry-After: 5

    + Attributes
        + message: `Generating PDF document timed out. Please try again later.` ( string )


## Pickup Lists [/pickup-lists]

### Get Pickup Lists [GET /pickup-lists{?carrierPickupListId}{?pickupDay}{?fromLastChanged}]

Returns pickup lists sorted by `lastChanged` in descending order.

Optionally, you can supply supported attributes to receive only pickup lists you want.

If you supply multiple parameters, then only one is applied, in following order:
1. carrierPickupListId
2. pickupDay
3. fromLastChanged

+ Parameters
    + carrierPickupListId: `123456` ( number, optional ) - ID of pickup list to get.
    + pickupDay: `2020-12-30` ( string, optional ) - Which day to get pickup lists for.
    + fromLastChanged: `2020-12-30T00:00:00.000Z` ( string, optional ) - ISO Date.

+ Request
    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)
    + Attributes (array[PickupLists])




## Pricing Report [/marketplace/{marketplace}/pricing-report{?access_token}]

+ Parameters
    + marketplace ( enum[string] )
        + Members
            + amazon_de
            + amazon_uk
            + amazon_nl
            + amazon_it
            + amazon_fr
            + amazon_es
            + amazon_mx
            + amazon_us
            + amazon_ca
            + amazon_br
            + amazon_jp
            + amazon_au
            + amazon_se
            + amazon_tr
            + amazon_pl
            + amazon_sg
            + amazon_be
    + access_token ( string, optional ) - API Bearer token, can be used to authorize without setting headers


### Get pricing report for marketplace [GET]

+ Request

    + Headers

            Authorization: Bearer <token>

+ Response 200 (text/xml)
    + Body
        <?xml version="1.0" encoding="UTF-8"?>
        <pricings>
            <pricing>
                <sku>XQ1R4</sku>
                <asin>B014SO8F7I</asin>
                <summary>
                    <seller>
                        <sellerId>BT2QPXXX4ZSL4</sellerId>
                        <landed>11.89</landed>
                        <listing>7.89</listing>
                        <shipping>4</shipping>
                        <isBuyBoxWinner>true</isBuyBoxWinner>
                    </seller>
                    <lowestPrice>
                        <channel>Merchant</channel>
                        <landed>11.71</landed>
                        <listing>11.71</listing>
                        <shipping>0</shipping>
                    </lowestPrice>
                    <buyBox>
                        <landed>11.89</landed>
                        <listing>7.89</listing>
                        <shipping>4</shipping>
                    </buyBox>
                    <totalOffers>8</totalOffers>
                </summary>
            </pricing>
        </pricings>

## Shipments [/shipments{?orderId}]

### Get order shipments [GET]
Returns all shipments for specific orderId. Each record contains only one type of item. Data from this endpoint are for Amazon fulfilled orders (FBA) only and are updated once a day due to Amazon's speed of updating.

(NOTE: Amazon made changes to their API and we are no longer able to obtain the following: billAddress, billCity, billState, billPostalCode, billCountry)

+ Parameters
    + orderId - string

+ Request

    + Headers

            Authorization: Bearer <token>


+ Response 200 (application/json)
    + Attributes ( array[ Shipment ] )

## Order Financial Events [/finances/orderevents{?fromPostedDate}]

### Get order financial events [GET]
Returns up to 100 events by posted date.
You can paginate naturally through events by taking `postedDate` attribute of the last event on a page and making the request again with this new value in your query.

+ Parameters
    + fromPostedDate - string - ISO date

+ Request

    + Headers

            Authorization: Bearer <token>


+ Response 200 (application/json)
    + Attributes ( array[ OrderFinancialEvent ] )

## Returns [/returns{?fromReturnDate}]

### Get order returns [GET]
Returns up to 100 records by return date.

Data from this endpoint are for Amazon fulfilled orders (FBA) only and are updated once a day.

+ Parameters
    + fromReturnDate - string - ISO date

+ Request

    + Headers

            Authorization: Bearer <token>


+ Response 200 (application/json)
    + Attributes ( array[ Return ] )

## Return Labels [/return-labels{?marketplace}{?marketplaceOrderId}]

### Create a return label request [POST]
Creates a return label request.

> **NOTE**: It is necessary to have a return address setup first. You must contact support.

+ Parameters
    + marketplace - string
    + marketplaceOrderId - string

+ Request

    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)
    + Attributes ( ReturnLabel )

### Get return label requests for order [GET]

+ Parameters
    + marketplace - string
    + marketplaceOrderId - string

+ Request

    + Headers

            Authorization: Bearer <token>

+ Response 200 (application/json)
    + Attributes ( array[ ReturnLabel ] )

# Data Structures

## Order (object)

+ marketplace ( MarketplaceName )
+ marketplaceOrderId: `xxxxxxxxxxxxxxxxx` ( string )
+ lastChanged: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
+ buyer ( Buyer )
+ delivery ( OrderDelivery, optional )
+ currencyCode: EUR ( string )
+ items ( array[ OrderItem ] )
+ fulfillmentChannel ( MarketplaceFulfillment )
+ status ( Status )
+ shippingPrice: 3.99 ( number ) - **Deprecated!** Use `price.delivery.[withTax|withoutTax]`
+ totalItemTax: 21.26 ( number ) - **Deprecated!** Use `price.items.tax`
+ totalDiscount: 3.99 ( number ) - **Deprecated!** Use `price.totalDiscount.[withTax|withoutTax]`
+ totalPrice: 121.89 ( number ) - **Deprecated!** Use `price.total.[withTax|withoutTax]`
+ price ( OrderPrice, required ) - Breakdown of order price.
+ payment ( Payment, required )
+ purchaseDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
+ pendingDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
+ unshippedDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
+ shippedDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
+ canceledDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
+ latestShipDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
+ latestDeliveryDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
+ shipServiceLevel: Expedited ( string )
+ deliveryBranchId ( number )
+ invoices ( array[ Invoice ] )
+ isBusinessOrder: false ( boolean )
+ isPremiumOrder: false ( boolean )
+ isPrime: false ( boolean )
+ isComplete: true ( boolean ) - If order has gathered all the information from marketplace.
+ isRefunded: false ( boolean )
+ paymentMethod ( PaymentMethod ) - **Deprecated!** Use `payment.paymentMethod` instead
+ invoiceUrls ( array[ string ] ) - **Deprecated!** Use `invoices` instead.
+ cashOnDelivery ( CashOnDelivery ) - **Deprecated!** Use `payment.cashOnDelivery` instead.
+ cancelRequest ( CancelRequest, optional )
+ returnLabels ( array[ OrderReturnLabel ], optional )

## OrderPrice (object)
+ items ( Price ) - Total price for order line items
+ delivery ( Price ) - Price of delivery
+ payment ( Price ) - Price of applied payment method (e.g. cash on delivery service fee)
+ totalDiscount ( Price ) - Total discount **applied** to order (amount is already subtracted from order total)
+ total ( Price, required ) - Order total price.

## Price (object)
+ withTax: 1200 ( number, optional ) - Price value incl. tax (is required if `withoutTax` is undefined)
+ withoutTax: 1000 ( number, optional ) - Price value excluding tax (is required if `withTax` is undefined)
+ tax: 200 ( number, optional ) - Value of applied tax
+ taxRatePercent: 20 ( number, optional ) - **Deprecated!** Use `taxRatePercentDecimal` instead - Integer tax rate in %
+ taxRatePercentDecimal: 20 ( number, optional ) - Decimal tax rate in %

## OrderItem (object)

+ sku: abc ( string ) - your ID of the product
+ asin: B005JID0ER ( string ) - amazon ID of the product
+ marketplaceItemId: 00000000000000 ( string )
+ name: example ( string )
+ price: 117.9 ( number ) - price of items with tax without shipping price
+ itemPrice: 58.95 ( number ) - price of one item (price divided by quantity)
+ quantity: 2 ( number )
+ tax: 21.26 ( number ) - tax for items (absolute number)
+ promotionDiscount: 0 ( number ) - **Deprecated!** Use `lineItemDiscount.[withTax|withoutTax]`
+ promotionDiscountTax: 0 ( number )  - **Deprecated!** Use `lineItemDiscount.tax`
+ shippingDiscount: 0 ( number )  - **Deprecated!** Use `deliveryDiscount.[withTax|withoutTax]`
+ shippingDiscountTax: 0 ( number ) - **Deprecated!** Use `deliveryDiscount.tax`
+ shippingPrice: 3.99 ( number )  - **Deprecated!** Use `deliveryPrice.[withTax|withoutTax]`
+ shippingTax: 0.72 ( number )  - **Deprecated!** Use `deliveryPrice.tax`
+ lineItemPrice ( Price, required ) - Price of the order line item (applied quantity).
+ lineItemDiscount ( Price ) - Applied discount for line item price.
+ deliveryPrice ( Price ) - Price for delivery of the line item (applied quantity).
+ deliveryDiscount ( Price ) - Applied discount for line item delivery price.
+ marketplaceCommission ( Price ) - Marketplace's commission on the ordered item.
+ buyerCustomInfo ( array[ BuyerCustomInfo ] )

## Buyer (object)

+ name: `name surname` ( string)
+ email: example@example.com ( string )
+ addressLine ( array[ string ] ) - max 3 items
+ city: city ( string )
+ countryCode: AA ( string )
+ country: country ( string )
+ district: district ( string )
+ phone: 00000000000 ( string )
+ zipCode: 00000000 ( string )
+ stateOrRegion: `state/region` ( string )
+ taxId: XX000000000 ( string )
+ taxCountry: AA ( string )

## OrderDelivery (object)

+ shippingCarrier: `Czech Post` ( string, optional )
+ shippingCarrierService: `Do ruky` ( string, optional )

## Payment (object)

+ paymentMethod ( OrderPaymentMethod, required )
+ cashOnDelivery ( PaymentCashOnDelivery, optional )

## PaymentCashOnDelivery (object)
+ toPay (number, optional)
+ servicePrice (number, optional)

## MarketplaceName (enum)
- amazon_de
- amazon_uk
- amazon_nl
- amazon_it
- amazon_fr
- amazon_es
- amazon_mx
- amazon_us
- amazon_ca
- amazon_br
- amazon_jp
- amazon_au
- amazon_se
- amazon_tr
- amazon_pl
- amazon_sg
- amazon_be
- mall_cz
- mall_sk
- mall_pl
- mall_si
- alza_cz
- emag_pl
- emag_hu
- emag_ro
- emag_bg
- kaufland_de
- kaufland_cz
- kaufland_sk
- kaufland_at
- kaufland_pl
- cdiscount_fr
- allegro_cz
- allegro_pl
- allegro_sk
- limetka_cz
- limetka_gr
- limetka_sk
- baskedo_bg
- baskedo_hu
- bol_nl
- ebay_at
- ebay_cz
- ebay_fr
- ebay_pl
- ebay_de
- ebay_us
- ebay_uk

## MarketplaceFulfillment (enum)
- Seller
- MediatedCarrier
- FBA

## Status (enum)
- Unshipped
- Pending
- Shipped
- Canceled

## PaymentMethod (enum)
- Other
- COD
- CVSs

## OrderPaymentMethod (enum)
- CreditCard
- CashOnDelivery

## BuyerCustomInfo (object)
+ name: `CustomizedURL` ( string )
+ value: `https://zme-caps.amazon.com/t/xxxxxxxxxxxx/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/00` ( string )

## PackageItem (object)
+ marketplaceItemId: `ID12340` (string, required) - Alza: item identifier | Amazon: orderItemId
+ quantity: `2` (number, required) - minimal value 0

## package (object)
+ number: `PK001` (string, required) - Alza: package identifier | Amazon: packageReferenceId seller-supplied identifier
+ weight: `2.5` (number, required) - Alza: Minimal value 0.1 | Amazon: Not used
+ fullNumber: `12345` (string, nullable) - Alza: trackingNumber | Amazon: trackingNumber
+ items: (array[PackageItem], required) - Items included in package

## InputFulfillment
+ marketplaceOrderId: `xxxxxxxxxxxxxxxxx` ( string, required )
+ marketplace ( MarketplaceName, required )
+ status ( FulfillmentStatus, required )
+ trackingNumber: 0000000000 ( string, nullable ) - **required for Mall & Alza**, for all statuses
+ fullNumber: 000000000000 ( string, nullable ) - **optional for Alza**, only applied if weight is provided
+ trackingUrl: `https://your-carrier.com/track/0000000000` ( string, nullable ) - **required for Mall**
+ carrier ( CarrierCode )
+ carrierName ( string, nullable )
+ shipDate: `2019-01-01T00:00:00.000Z` ( string, nullable ) - ISO date
+ weight: `5` (number) - **required for Alza** in `Shipped` status
+ cashOnDeliveryValue: `890` (number) - **required for Alza** in `Shipped` status
+ cashOnDeliveryCurrency: `CZK` (string) - **required for Alza** in `Shipped` status
+ shipmentValue: `890` (number) - **required for Alza** in `Shipped` status
+ shipmentValueCurrency: `CZK` (string) - **required for Alza** in `Shipped` status
+ parcelShop (ParcelShop) - **optional for Alza** in `Shipped` status
+ parcelShopBranchCode (string) - **optional for Alza** in `Shipped` status
+ cancelReason (CancelReason) - **optional for Amazon** in `Canceled` status
+ shipMethod: `DHL Express` ( string, optional ) - **optional for Amazon**
+ packages (array[package], optional) - **optional for Alza & Amazon** List of packages included in the fulfillment


## CashOnDelivery
+ value: 0 ( number )
+ currency: EUR ( string )
+ variableSymbol ( string )

## CancelRequest
+ cancelReason: BuyerCanceled ( CancelReason )
+ marketplaceCancelReason ( string )

## OrderReturnLabel
+ status ( OrderReturnLabelStatus, required )
+ requestCreatedAt ( string, required )
+ shipmentNumber ( string, required )
+ labelNumber ( number, required )
+ packageLabelUrls ( array[ string ], required )
+ errorMessage ( string, optional )


## Invoice
+ id: `INV-FR-000000000-2019-00` ( string )
+ type: `SHIPMENT` ( string ) - Expected values are SHIPMENT and REFUND
+ url: `https://www.Amazon.fr/gp/invoice/download.html?v=urn%3aalx%3aver%3a01dcc42c-0000-000a-aaa0-00000a000aa0&t=EU_Retail_Forward` ( string )
+ date: `2019-01-01T00:00:00.000Z` ( string ) - ISO date

## Fulfillment
+ marketplaceOrderId: `xxx-xxxxxxx-xxxxxxx` ( string, required )
+ marketplaceOrderIds: `xxx-xxxxxxx-xxxxxxx` ( array [string], required )
+ marketplace ( MarketplaceName, required )
+ status ( FulfillmentStatus, required )
+ trackingNumber: 0000000000 ( string, optional )
+ trackingUrl: `https://your-carrier.com/track/0000000000` ( string, optional )
+ carrier ( CarrierCode )
+ carrierName ( string, optional )
+ shipDate: `2019-01-01T00:00:00.000Z` ( string, nullable ) - ISO date
+ lastChanged: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
+ shipMethod: `DHL Express` ( string, optional )

## FulfillmentStatus ( enum )
- Registered
- Shipped
- AtDepot
- OutForDelivery
- Delivered
- Failed
- Canceled


## ParcelShop (enum)
+ CZPOSTB
+ CZPOSTP
+ DPDALZABOX
+ DPDBOX
+ DPDPARCELSHOP
+ GEISPOINT
+ PPLPARCELSHOP
+ ZASILKOVNA

## CarrierCode ( enum )
+ DPD
+ GLS
+ UPS

+ ALZA - Alza only
+ ALZABOX - Alza only
+ ALZABRANCH - Alza only
+ COURIER - Alza only
+ CZPOSTB - Alza only
+ CZPOSTD - Alza only
+ CZPOSTP - Alza only
+ DPDALZABOX - Alza only
+ DPDBOX - Alza only
+ DPDPARCELSHOP - Alza only
+ FOFRSTD - Alza only
+ GebruderWeissStandard - Alza only
+ GEISCARGO - Alza only
+ GEISPOINT - Alza only
+ HELICARSTD - Alza only
+ HELICARUP - Alza only
+ MagyarPOSTHD - Alza only
+ MagyarPOSTPO - Alza only
+ MagyarPOSTPP - Alza only
+ MagyarPOSTPT - Alza only
+ PPLPARCELSHOP - Alza only
+ RHENUS - Alza only
+ SKPOSTD - Alza only
+ SKPOSTP - Alza only
+ SKYNET - Alza only
+ TOPTRANS - Alza only
+ WEDOHD - Alza only
+ ZASILKOVNA - Alza only
+ ZavolejSiKuryra - Alza only
+ Supplier - Alza only (Have to fill in `carrierName`)

+ DHL - Alza, Amazon, Kaufland
+ GO - Alza, Amazon, Kaufland

+ GEIS - Alza, Kaufland
+ PPL - Alza, Kaufland

+ A1 - Amazon only
+ AAACooper - Amazon only
+ ABF - Amazon only
+ ALLJOY - Amazon only
+ AMAUK - Amazon only
+ AMAZONHORIZON - Amazon only
+ AmazonShipping - Amazon only
+ AMZL - Amazon only
+ AMZLUK - Amazon only
+ Andere - Amazon only
+ Anjun - Amazon only
+ AO - Amazon only
+ AODeutschland - Amazon only
+ APC - Amazon only
+ APCOvernight - Amazon only
+ APCPOSTALLOGISTICS - Amazon only
+ APGeCommerce - Amazon only
+ ARAS - Amazon only
+ ArasKargo - Amazon only
+ ArcoSpedizioni - Amazon only
+ Arkas - Amazon only
+ ArrowXL - Amazon only
+ Asendia - Amazon only
+ Asgard - Amazon only
+ Assett - Amazon only
+ ATS - Amazon only
+ AUSSIEPOST - Amazon only
+ AustraliaPost - Amazon only
+ AustraliaPostArticleID - Amazon only
+ AustraliaPostConsignment - Amazon only
+ B2C - Amazon only
+ B2CEurope - Amazon only
+ B2CShip - Amazon only
+ Balnak - Amazon only
+ Bartolini - Amazon only
+ BeijingQuanfengExpress - Amazon only
+ BestBuy - Amazon only
+ BestExpress - Amazon only
+ BetterTrucks - Amazon only
+ BJS - Amazon only
+ Blowhorn - Amazon only
+ Bombax - Amazon only
+ BombinoExpress - Amazon only
+ BPOST - Amazon only
+ BR1Express - Amazon only
+ BRT - Amazon only
+ Buylogic - Amazon only
+ Cainiao - Amazon only
+ Canpar - Amazon only
+ CargoLine - Amazon only
+ Caribou - Amazon only
+ Cart2India - Amazon only
+ CBHub - Amazon only
+ CBL - Amazon only
+ CDC - Amazon only
+ CELERITAS - Amazon only
+ Centex - Amazon only
+ CEVA - Amazon only
+ CevaLojistik - Amazon only
+ ChronoExpress - Amazon only
+ Chukou1 - Amazon only
+ Cititrans - Amazon only
+ CityPost - Amazon only
+ CNE - Amazon only
+ Coliposte - Amazon only
+ ConsegnaMezziPropri - Amazon only
+ Conway - Amazon only
+ Correios - Amazon only
+ Correos - Amazon only
+ CorreosExpress - Amazon only
+ COSCO - Amazon only
+ CouriersPlease - Amazon only
+ CTTExpress - Amazon only
+ Cubyn - Amazon only
+ CyberSavings - Amazon only
+ DACHSER - Amazon only
+ DAIPOST - Amazon only
+ DELDeliveries - Amazon only
+ Delivengo - Amazon only
+ DeliveryGroup - Amazon only
+ DerKurier - Amazon only
+ DFL - Amazon only
+ DHLeCommerce - Amazon only
+ DHLFreight - Amazon only
+ DHLHomeDelivery - Amazon only
+ DHLKargo - Amazon only
+ DHLPaket - Amazon only
+ DHLParcelUK - Amazon only
+ DHLPL - Amazon only
+ DigitalDelivery - Amazon only
+ DirectLog - Amazon only
+ Dotzot - Amazon only
+ DPB - Amazon only
+ DPDLocal - Amazon only
+ DSV - Amazon only
+ DX - Amazon only
+ DXExpress - Amazon only
+ DXFreight - Amazon only
+ DXSecure - Amazon only
+ DYNAMICEXPRESS - Amazon only
+ ECMS - Amazon only
+ ECMSexpress - Amazon only
+ EcomExpress - Amazon only
+ EcomShippingSolutionsPVTltd - Amazon only
+ EINSASOURCING - Amazon only
+ EKITrans - Amazon only
+ EmiratesPost - Amazon only
+ Emons - Amazon only
+ Endopack - Amazon only
+ Energo - Amazon only
+ Envialia - Amazon only
+ ePostGlobal - Amazon only
+ Equick - Amazon only
+ ESNAD - Amazon only
+ Estafeta - Amazon only
+ Estes - Amazon only
+ EUB - Amazon only
+ Europaczka - Amazon only
+ Exapaq - Amazon only
+ FASTEST - Amazon only
+ FedexFreight - Amazon only
+ FERCAM - Amazon only
+ FilloKargo - Amazon only
+ FirstFlightChina - Amazon only
+ FirstMile - Amazon only
+ Fleetan - Amazon only
+ Flyt - Amazon only
+ FRACHTPOST - Amazon only
+ FRANCEEXPRESS - Amazon only
+ Gati - Amazon only
+ GEL - Amazon only
+ GELExpress - Amazon only
+ geodis - Amazon only
+ GeodisCalberson - Amazon only
+ GeopostKargo - Amazon only
+ GFS - Amazon only
+ GLSCanada - Amazon only
+ Gojavas - Amazon only
+ GRUPOLOGISTIC - Amazon only
+ Hellmann - Amazon only
+ Heppner - Amazon only
+ HermesCorporate - Amazon only
+ HermesEinrichtungsservice - Amazon only
+ HermesUK - Amazon only
+ Hlog - Amazon only
+ HNC - Amazon only
+ HomeLogistics - Amazon only
+ honesteye - Amazon only
+ HongkongPost - Amazon only
+ HorozLojistik - Amazon only
+ HotpointLogistics - Amazon only
+ HRP - Amazon only
+ HScode - Amazon only
+ HUAHANLogistics - Amazon only
+ HubEurope - Amazon only
+ HunterExpress - Amazon only
+ HunterLogistics - Amazon only
+ Huxloe - Amazon only
+ HuxloeLogistics - Amazon only
+ ICCWorldwide - Amazon only
+ IDS - Amazon only
+ IDSNetzwerk - Amazon only
+ iMile - Amazon only
+ Interlink - Amazon only
+ Interno - Amazon only
+ Intersoft - Amazon only
+ iParcel - Amazon only
+ ITDGlobal - Amazon only
+ JampTExpress - Amazon only
+ JapanPost - Amazon only
+ JCEX - Amazon only
+ JerseyPost - Amazon only
+ Jiufang - Amazon only
+ JPLUPU - Amazon only
+ JSExpress - Amazon only
+ JT - Amazon only
+ JTExpress - Amazon only
+ JYExpress - Amazon only
+ Kargokar - Amazon only
+ KEAVO - Amazon only
+ Kerry - Amazon only
+ KuehneNagel - Amazon only
+ Kybotech - Amazon only
+ Landmark - Amazon only
+ LandmarkGlobal - Amazon only
+ Lemonmode - Amazon only
+ Letian - Amazon only
+ LFLogistic - Amazon only
+ Liccardi - Amazon only
+ LiccardiTrasporti - Amazon only
+ LogistikGruppe - Amazon only
+ Loomis - Amazon only
+ MailAlliance - Amazon only
+ MailAmericas - Amazon only
+ Mainpost - Amazon only
+ MBE - Amazon only
+ MetroKargo - Amazon only
+ Mezzipropri - Amazon only
+ MHI - Amazon only
+ Milkman - Amazon only
+ MNGKargo - Amazon only
+ MZZBriefdienst - Amazon only
+ Nacex - Amazon only
+ NAQELEXPRESS - Amazon only
+ NarpostKargo - Amazon only
+ NewZealandPost - Amazon only
+ Nexive - Amazon only
+ Ninjavan - Amazon only
+ NOVEO - Amazon only
+ NowBikes - Amazon only
+ NTL - Amazon only
+ OCSWorldwide - Amazon only
+ OldDominion - Amazon only
+ OneWorldExpress - Amazon only
+ ONTIME - Amazon only
+ OSMWorldwide - Amazon only
+ Otro - Amazon only
+ Palletline - Amazon only
+ Palletways - Amazon only
+ Panther - Amazon only
+ Paquetexpress - Amazon only
+ Parcel2go - Amazon only
+ ParcelDenOnline - Amazon only
+ ParcelHub - Amazon only
+ Parcelhub - Amazon only
+ ParcelinkLogistics - Amazon only
+ ParcelMonkey - Amazon only
+ ParcelOne - Amazon only
+ ParcelStation - Amazon only
+ PDCLogistics - Amazon only
+ Pilot - Amazon only
+ PilotFreight - Amazon only
+ PIN - Amazon only
+ PolishPost - Amazon only
+ PosLaju - Amazon only
+ PostModern - Amazon only
+ PTTKargo - Amazon only
+ PUROLATOR - Amazon only
+ Quantium - Amazon only
+ Qxpress - Amazon only
+ RabenGroup - Amazon only
+ RBNA - Amazon only
+ Redpack - Amazon only
+ REDUR - Amazon only
+ Rhenus - Amazon only
+ Rieck - Amazon only
+ Rivigo - Amazon only
+ RL - Amazon only
+ RMLGB - Amazon only
+ Roadrunner - Amazon only
+ RRDonnelley - Amazon only
+ Safexpress - Amazon only
+ Saia - Amazon only
+ Sailpost - Amazon only
+ SchweizerPost - Amazon only
+ Seino - Amazon only
+ SEINOTRANSPORTATION - Amazon only
+ SekoLogistics - Amazon only
+ SelemKargo - Amazon only
+ SelfDelivery - Amazon only
+ Sendcloud - Amazon only
+ Sending - Amazon only
+ SENDLE - Amazon only
+ Seur - Amazon only
+ SevenSenders - Amazon only
+ SFC - Amazon only
+ SHIPA - Amazon only
+ ShipDelight - Amazon only
+ ShipEconomy - Amazon only
+ ShipEntegra - Amazon only
+ ShipGlobal - Amazon only
+ ShipGlobalUS - Amazon only
+ Shipmate - Amazon only
+ Shippit - Amazon only
+ ShopiniWorld - Amazon only
+ ShreeMarutiCourier - Amazon only
+ ShreeTirupatiCourier - Amazon only
+ ShunfengExpress - Amazon only
+ Sinerlog - Amazon only
+ Sinotrans - Amazon only
+ Skypostal - Amazon only
+ Smartrlogistics - Amazon only
+ SMSA - Amazon only
+ SMSAExpress - Amazon only
+ Soarmall - Amazon only
+ Sonstige - Amazon only
+ SouthEasternFreightLines - Amazon only
+ Speedaf - Amazon only
+ Speedex - Amazon only
+ Spoton - Amazon only
+ springGDS - Amazon only
+ Sprint - Amazon only
+ StahlmannandSachs - Amazon only
+ Stampit - Amazon only
+ Staples - Amazon only
+ StarTrackArticleID - Amazon only
+ StarTrackConsignment - Amazon only
+ STG - Amazon only
+ STOExpress - Amazon only
+ Sunyou - Amazon only
+ Susa - Amazon only
+ Swisspost - Amazon only
+ Szendex - Amazon only
+ TATAExpress - Amazon only
+ TDN - Amazon only
+ TeamExpress - Amazon only
+ TezelLojistik - Amazon only
+ TheDeliveryGroup - Amazon only
+ TheProfessionalCouriers - Amazon only
+ ThreeHundredSixtylion - Amazon only
+ TIPSA - Amazon only
+ TNTIT - Amazon only
+ TNTKargo - Amazon only
+ Toll - Amazon only
+ TollGlobalExpress - Amazon only
+ TongdaGlobal - Amazon only
+ Topyou - Amazon only
+ TotalExpress - Amazon only
+ Tourline - Amazon only
+ Trackon - Amazon only
+ Trakpak - Amazon only
+ Transaher - Amazon only
+ TransFolha - Amazon only
+ Translink - Amazon only
+ TransoFlex - Amazon only
+ Truline - Amazon only
+ TSB - Amazon only
+ Tuffnells - Amazon only
+ TWS - Amazon only
+ TXT - Amazon only
+ TyD - Amazon only
+ UBI - Amazon only
+ UKMail - Amazon only
+ UniUni - Amazon only
+ UPakWeShip - Amazon only
+ UPSFreight - Amazon only
+ Upsilon - Amazon only
+ UrbanExpress - Amazon only
+ Uship - Amazon only
+ VerageShipping - Amazon only
+ ViaXpress - Amazon only
+ VIR - Amazon only
+ VNLIN - Amazon only
+ WatkinsandShepard - Amazon only
+ Wefast - Amazon only
+ WeWorldExpress - Amazon only
+ Whistl - Amazon only
+ Whizzard - Amazon only
+ WINIT - Amazon only
+ WPX - Amazon only
+ XDP - Amazon only
+ XPO - Amazon only
+ XPOFreight - Amazon only
+ Xpressbees - Amazon only
+ YANWEN - Amazon only
+ YDH - Amazon only
+ YellowFreight - Amazon only
+ YFHEX - Amazon only
+ YFLogistics - Amazon only
+ YHT - Amazon only
+ Yodel - Amazon only
+ YTOExpress - Amazon only
+ YundaExpress - Amazon only
+ ZADExpress - Amazon only
+ Zeleris - Amazon only
+ ZTOExpress - Amazon only
+ ZustAmbrosetti - Amazon only

+ ChinaPost - Amazon, Cdiscount
+ DBSchenker - Amazon, Cdiscount
+ DHLExpress - Amazon, Cdiscount
+ FourPX - Amazon, Cdiscount
+ Hermes - Amazon, Cdiscount
+ MondialRelay - Amazon, Cdiscount
+ SFExpress - Amazon, Cdiscount
+ SingaporePost - Amazon, Cdiscount
+ WanbExpress - Amazon, Cdiscount
+ YunExpress - Amazon, Cdiscount

+ Chronopost - Amazon, Cdiscount, Kaufland
+ Colissimo - Amazon, Cdiscount, Kaufland
+ FedEx - Amazon, Cdiscount, Kaufland
+ PostNL - Amazon, Cdiscount, Kaufland
+ Spring - Amazon, Cdiscount, Kaufland
+ TNT - Amazon, Cdiscount, Kaufland
+ Other - Amazon, Cdiscount, Kaufland (Have to fill in `carrierName`)

+ AFLFedex - Amazon, Kaufland
+ Aramex - Amazon, Kaufland
+ ATPOST - Amazon, Kaufland
+ BlueDart - Amazon, Kaufland
+ BluePackage - Amazon, Kaufland
+ CanadaPost - Amazon, Kaufland
+ CityLink - Amazon, Kaufland
+ Delhivery - Amazon, Kaufland
+ DeutschePost - Amazon, Kaufland
+ DHLGlobalMail - Amazon, Kaufland
+ DTDC - Amazon, Kaufland
+ Fastway - Amazon, Kaufland
+ FEDEXJP - Amazon, Kaufland
+ FedExSmartPost - Amazon, Kaufland
+ FirstFlight - Amazon, Kaufland
+ HermesLogistikGruppe - Amazon, Kaufland
+ IndiaPost - Amazon, Kaufland
+ InPost - Amazon, Kaufland
+ JPEXPRESS - Amazon, Kaufland
+ LaPoste - Amazon, Kaufland
+ Lasership - Amazon, Kaufland
+ MRW - Amazon, Kaufland
+ Newgistics - Amazon, Kaufland
+ NipponExpress - Amazon, Kaufland
+ NITTSU - Amazon, Kaufland
+ OnTrac - Amazon, Kaufland
+ OSM - Amazon, Kaufland
+ OverniteExpress - Amazon, Kaufland
+ Parcelforce - Amazon, Kaufland
+ Parcelnet - Amazon, Kaufland
+ PosteItaliane - Amazon, Kaufland
+ PostNord - Amazon, Kaufland
+ Professional - Amazon, Kaufland
+ RoyalMail - Amazon, Kaufland
+ SAGAWA - Amazon, Kaufland
+ SagawaExpress - Amazon, Kaufland
+ SDA - Amazon, Kaufland
+ Smartmail - Amazon, Kaufland
+ Streamlite - Amazon, Kaufland
+ Target - Amazon, Kaufland
+ UPSMailInnovations - Amazon, Kaufland
+ UPSMI - Amazon, Kaufland
+ USPS - Amazon, Kaufland
+ YAMATO - Amazon, Kaufland
+ YamatoTransport - Amazon, Kaufland

+ AsendiaHK - Cdiscount
+ Bpost - Cdiscount
+ ChinaEMS_ePacket - Cdiscount
+ Chronofresh - Cdiscount
+ CNEExpress - Cdiscount
+ ColisPrive - Cdiscount
+ DHLDeutschePost - Cdiscount
+ DHLEcommerceAsia - Cdiscount
+ FastWL - Cdiscount
+ GEODIS - Cdiscount
+ LaPosteCourrier - Cdiscount
+ MalaysiaPost - Cdiscount
+ RelaisColis - Cdiscount
+ SFCService - Cdiscount
+ WishPost - Cdiscount
+ Yanwen - Cdiscount

+ CZECHPOST - Kaufland
+ OTHER - Kaufland
+ Packeta - Kaufland
+ SPS - Kaufland
+ WEDOLOGISTICS - Kaufland

## Shipment (object)
- marketplace: amazon_de (string) - can be empty
- marketplaceOrderId: `xxx-xxxxxxx-xxxxxxx` (string)
- shipmentId: DckjR9T7L (string)
- shipmentItemId: DYr1tCWKR (string)
- sku (string)
- quantity (number)
- sellerCentralId: MUC3 (string)
- carrier (string)
- trackingNumber: AA0000000000 (string)
- billAddress (string) - can be empty - see NOTE
- billCity (string) - can be empty - see NOTE
- billState (string) - can be empty - see NOTE
- billPostalCode (string) - can be empty - see NOTE
- billCountry (string) - can be empty - see NOTE
- currency: EUR (string)
- itemPromotionDiscount: 0 (number)
- shipPromotionDiscount: `-1.2` (number)
- shipmentDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
- estimatedArrivalDate: `2019-01-03T00:00:00.000Z` ( string ) - ISO date

## AmountItem (object)
- name ( string )
- amount ( number )

## AdditionalFinancialItem (object)
- type: `TaxWithheld` ( string )
- taxCollectionModel: `MarketplaceFacilitator`  ( string )
- chargeType: `MarketplaceFacilitatorVAT-Principal` ( string )
- amount: 12.34 ( number )

## OrderFinancialEventItem (object)
- itemId: 00000000000000 ( string )
- quantity ( number )
- sku ( string )
- name ( string )
- charges ( array[AmountItem] )
- fees ( array[AmountItem] )
- additionalItems ( array[AdditionalFinancialItem] )
- costOfPointsGranted ( number )
- costOfPointsReturned ( number )
- withheldTax ( number )
- promotions ( number )
- currency: EUR ( string )

## OrderFinancialEventType (enum)
- Payment
- Refund
- Chargeback

## OrderFinancialEvent (object)
- marketplaceOrderId: `xxx-xxxxxxx-xxxxxxx` ( string )
- marketplace: amazon_de ( MarketplaceName )
- postedDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
- type ( OrderFinancialEventType )
- items ( array[OrderFinancialEventItem] )

## Return (object)
- returnDate: `2019-01-01T00:00:00.000Z` ( string ) - ISO date
- marketplaceOrderId: `xxx-xxxxxxx-xxxxxxx` ( string )
- sku ( string )
- asin ( string )
- fnSku ( string )
- productName ( string )
- quantity ( number )
- fulfillmentCenterId ( string )
- detailedDisposition ( string )
- reason ( string )
- status ( string )
- licensePlateNumber ( string )
- customerComments ( string )

## PackageLabelData
+ status ( ResourceStatuses ) 
+ packageLabels: https://url.to/pdf?abcasdasdasd ( string, optional )
+ packageLabelsId: `abc-123-456` ( string )
+ packages ( array[ FulfillmentPackage ] )
+ failReason: Maximum number of required packages exceeded. Actual limit is 1.  ( string )

## LabelMarketplace (enum)
- alza_cz

## CreateLabelInput
+ marketplaceOrderIds: `abc-123-456`, `efg-456-789` ( array[string], required )
+ packages ( array[PackageInput], optional )


## PackageInput
+ weight: 3 ( number, required )
+ items ( array[PackageInputItem] )

## PackageInputItem
+ marketplaceOrderId: `moi-123-xxx` ( string, required )
+ marketplaceItemId: `mid-123-zzz` ( string, required )
+ quantity: 1 ( number, required )

## ResourceStatuses (enum)
- Generated
- Generating
- Failed

## CancelReason (enum)
+ NoInventory
+ ShippingAddressUndeliverable
+ CustomerExchange
+ BuyerCanceled
+ GeneralAdjustment
+ CarrierCreditDecision
+ RiskAssessmentInformationNotValid
+ CarrierCoverageFailure
+ CustomerReturn
+ MerchandiseNotReceived
+ CannotVerifyInformation
+ PricingError
+ RejectOrder
+ WeatherDelay

## OrderReturnLabelStatus (enum)
+ Pending
+ Creating
+ Created
+ Error

## FulfillmentPackageItem
+ marketplaceItemId: `123-1bc-222` ( string )
+ marketplaceOrderId: `abc-efg-145` ( string )
+ quantity ( number )


## FulfillmentPackage
+ weight: 3 ( number )
+ items ( array[FulfillmentPackageItem] )

## ShippingList
+ shippingListId: 123-abcd-456 ( string, required )
+ pdf: www.example.com ( string, required )

## AlzaShipment
+ departureTime: `2019-01-01T00:00:00.000Z` ( string, optional ) - ISO date
+ shippingList ( ShippingList, required )

## BranchBarcodesBatchInput
+ marketplaceOrderIds: 4252154192, 4251962062 ( array[string], required )
+ operation: `BarcodeBatch` (enum[string], optional ) - Operation what will be used to generate document
    + Members
        + `BarcodeBatch`
        + `BarcodeWithEanBatch`

## BranchBarcodesBatch
+ pdfId: `5f64578e2feb3dc8f4703749` ( string, required ) - Unique ID of the generated PDF document
+ pdfDocumentType: `BarcodeBatch` (enum[string], required ) - Operation used to generate document
    + Members
        + `BarcodeBatch`
        + `BarcodeWithEanBatch`
+ downloadUrl: https://download.link.com/for/document.pdf ( string, required ) - Download URL of the generated PDF document
+ barcodes: BCX846680925,BCX846442464 ( array[ string ], required ) - Barcodes that are present in the generated PDF document (can contain duplicates)

## PickupLists 
 + carrier: DHL ( CarrierCode, required ) - Shipping carrier
 + carrierPickupListId: 123456 ( number, required ) - Carrier's identification of the pickup list
 + pickupTime: `2020-12-30T00:00:00.000Z` ( string, required ) - Expected time of pickup by the carrier, in UTC
 + downloadUrl: `https://download.link.com/for/document.pdf` ( string, required ) - Download URL of the pickup list in PDF
 + marketplaceOrderIds: `abc-123-456`, `efg-456-789` ( array[string], required ) - `marketplaceOrderId`s of orders included on this pickup list
 + lastChanged: `2020-12-30T00:00:00.000Z` ( string, required ) - Time of the last change made to the pickup list, in UTC

## ReturnLabel
+ marketplace: amazon_de ( string, required )
+ marketplaceOrderId: 123-1234567-123 ( string, required )
+ state: Resolved ( ReturnLabelState, required )
+ referenceId: return-amazon-de-123-1234567-123 ( string, required )
+ note: Company XYZ ( string, optional )
+ sender ( Address, required )
+ recipient ( Address, required )
+ createdAt: `2020-12-30T00:00:00.000Z` ( string, required )
+ returnLabelUrls ( array[ string ], optional )
+ error ( string, optional )

## ReturnLabelState (enum)
+ RequestingLabel
+ ResolvingLabel
+ Resolved
+ Error

## Address
+ companyName: Company XYZ ( string, optional )
+ name: John Dow ( string, required )
+ countryCode: AA ( string, required )
+ city: City ( string, required )
+ zipCode: 123456 ( string, required )
+ street: Street 123 ( string, required )
+ phone: 123456789 ( string, optional )
+ email: example@email.cmo ( string, optional )
