FORMAT: 1A
HOST: https://diamond.labelprinter.cz/

# Label Printer API

Aplikace **Label Printer** poskytuje `RESTful` `API` rozhraní pro snadné napojení Vaší aplikace (účetní programy jako jsou Pohoda, K2, Helios Altus Vario, 
Winduo64 apod., eshopová řešení či jiné klientské aplikace) na naší aplikaci pro automatizovaný tisk přepravních etiket a 
zefektivnění celého procesu expedice. Na účetní programy se umíme napojit i přímo. Proto nás neváhejte kontaktovat a my Vám rádi poradíme, 
které napojení bude pro Vás nejvhodnější.

> **+420 776 329 729, tomas.loskot@diamondsoftware.cz**

## Způsob komunikace
Komunikace probíhá zabezpečeně přes protokol `HTTPS` na url adrese, na které se před využitím obě strany dohodnou 
(formát bude `https://vasefirma.labelprinter.cz`).

+ Data budou přebírána v `JSON` formátu a stejný formát bude i v `http` odpovědích
+ V hlavičce `http` požadavku uvádějte `Content-Type` s hodnotou `application/json` (kromě požadavku vyžadující přístupový token, kde se vyžaduje jiný formát)
+ V případě požadavku na přístupový token uvádějte v hlavičce v parametru `Content-Type` hodnotu `application/x-www-form-urlencoded`

## Zabezpečení
Komunikace mezi aplikací **Label Printer** a Vaší stranou bude probíhat zabezpečeně pomocí `OAuth 2.0`
protokolu s hodnotou parametru `grant_type` nastavenou na `client_credentials`. Příklad komunikace na zisk přepravců metodou `GET` probíhá následovně.

+ Vaše aplikace `POST` požadavkem na url adresu (např. `https://diamond.labelprinter.cz/connect/token`) zažádá o přístupový token
+ `URI` pro zisk tokenu bude vždy `https://xxx.labelprinter.cz/connect/token`. XXX bude nahrazeno za název, který bude využívat Vaše firma.
+ `Content-Type` nastavíte na hodnotu `application/x-www-form-urlencoded`
+ Do těla požadavku uvedete parametr `grant_type` s hodnotou `client_credentials` a parametr `scope` na hodnotu, která Vám bude při domluvě zaslána
+ Je potřeba rovněž uvést přístupové údaje v parametrech `client_id` a `client_secret`, které rovněž dostanete po domluvě. 
+ Naše `API` podporuje zadání přístupových údajů jak v těle `POST` požadavku tak zabezpečeně v hlavičce pomocí `Basic autentikace` (viz příklad níže)
+ V odpovědi v případě úspěchu dostanete přístupový token. V případě neúspěchu pak návratový http stavový kód `401 UNAUTHORIZED`
+ Následně v požadavku na url adresu (např. `https://diamond.labelprinter.cz/shippers`) zadáte v hlavičce přístupový token (např. `Authorization: Bearer d77d0eb0684d1360ae74811ed59f546e`)
+ V případě úspěchu dostanete v odpovědi seznam přepravců v `JSON` formátu

**Příklad požadavku na přístupový token**
```
POST /connect/token HTTP/1.1
Host: localhost:5000
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZGlhbW9uZDpEWW5BeUdHalpvQ283dXhsYjlQYU1SVDNtbGo3b0pIS3NBPT0=
Cache-Control: no-cache

grant_type=client_credentials&scope=lp_api_full
```

**Příklad požadavku na zisk přepravců**
```
GET /shippers HTTP/1.1
Host: localhost:5000
Authorization: Bearer d77d0eb0684d1360ae74811ed59f546e
Cache-Control: no-cache
```

## Požadavky a odpovědi
Naše `API` příjmá požadavky metodami `GET`, `POST`, `PUT` a `DELETE`. Datový formát pro přenos je výhradně `application/json`. 
Strukturu najdete v jednotlivých sekcích níže. Odpověď pak rovněž dostanete ve formátu `application/json` v pevně stanovené 
struktuře. Konkrétní struktury pak najdete v sekcích příkladů jednotlivých možných požadavků.

**Příklad kladné odpovědi (Http kód 2xx)**
```
{
    "code": 200,
    "data": [
        {
            "code": "CP",
            "name": "Česká pošta, s.p.",
            "phone": "+420 840 111 244",
            "email": "info@cpost.cz"
        },
        ...
    ],
    "errors": []
}
```

**Příklad chybné odpovědi (4xx, 500)**
```
{
    "code": 422,
    "data": [],
    "errors": [
        {
            "message": "Není vyplněn variabilní symbol",
            "field": "variableSymbol"
        }
    ]
}
```

**Význam jednotlivých polí**
+ **"code"** - Stavový kód `HTTP` odpovědi.
    + `200` - Požadavek byl úspěšně zpracován
    + `201` - Požadavek byl úspěšně zpracován. Typicky je vrácen při `POST`, `PUT` metodách, které vkládají data do aplikace **Label Printer**
    + `400` - Požadavek nemůže být zpracován. Chyb může být několik (špatná syntaxe požadavku, špatné přístupové údaje při zisku tokenu apod.). Pokud v odpovědi dostáváte zprávu **Invalid client**, znamená to, že pro přístupový token jste zadali špatné údaje (client_id nebo client_secret). 
    + `401` - Přístup byl zamítnut. Přístup k `API` byl zamítnutý např. z důvodu vypršení přístupového tokenu (hodnota expirace je typicky 30 minut)
    anebo jste před konkrétním požadavkem nejdříve nezažádali o přístupový token.
    + `404` - Daná metoda nebyla nalezena a zřejmě ji `API` nevyužívá popř. metoda, která vrací detail dle vstupního id a takový detail nebyl nalezen.
    + `422` - Požadavek nebyl úspěšně zpracován. Vstup je sice v pořádku, ale neprošel validací v aplikaci **Label Printer** (např. chybí nějaký povinný údaj)
    + `500` - Interní chyba systému. Chyba je nejspíš na naší straně a proto nás prosím kontaktujte.
+ **"data"** - Zde obdržíte data, o které žádáte. Např. seznam přepravců, sledovací čísla balíků, stav zásilky, etikety zásilek atd.
+ **"errors"** - V případě chyby zde obdržíte informace, k jaké chybě došlo popř. bude vyplněno pole `field`, kde najdete informaci, které pole chybu způsobilo.

> Vždy je vyplněno pouze jedno z polí `data` anebo `errors`. Nikdy nejsou vyplněny obě pole zároveň. V případě úspěšného zpracování požadavku bude vyplněno pole `data` 
a naopak, pokud požadavek úspěšně zpracová nebyl, bude vyplněné pole `errors` s příslušnými chybami. Pokud zásilka bude uložena v systému **Label Printer** 
a obsahuje nějaké chybové údaje, či jiné sdělení, lze toto dohledat v cestě `data[0].messages`.

> `LP API` lze využít ve dvou variantách. Výchozí varianta je, že v případě chyby se vrátí chyba zpět v `HTTP` 
odpovědi a data se do aplikace **Label Printer** neuloží. Oprava chyby je na systému, který s `LP API` komunikuje. 
Druhá varianta je, že v případě chyby se data do aplikace **Label Printer** uloží a oprava se zajistí v klientské 
aplikaci **Label Printer**. Druhou variantu lze zprovoznit tak, že v hlavičce `HTTP` požadavku zašlete parametr 
`LoaderMode` s nastavenou hodnotou `true` nebo `1`.

## Klient
Při tvorbě klientské části napojení se na naše `API`, které je výhradně ve Vaši režii, můžete využít příklady zdrojových kódů, 
které jsou uvedeny vždy v pravém sloupci u příslušných akcí (select box v části Request s výchozí hodnotou Raw). Pokud vyvíjíte v 
jazyce `C#`, je možné rovněž využít knihovnu `IdentityModel` pro jednodušší práci při napojení na `API`, kde se využívá pro 
zabezpečení `OAuth 2.0` protokol. Tato knihovna má spoustu "helper" funkcí, které Vám pomohou s implementací napojení na naše `API`. 
V konstruktoru třídy `TokenClient` lze definovat, že budete chtít přístupové údaje vkládat do hlavičky `POST` požadavku zabezpečeně pomocí 
`Basic autentizace`. Poté můžete zavolat metodu, která vytvoří požadavek s využitím `client_credentials` grantu (příklad jednoduchého 
kódu je uveden níže). Pro testování lze rovněž využít různé klientské aplikace. My většinou využíváme aplikaci 
<a href="https://www.getpostman.com/" target="_blank">POSTMAN</a> (anebo jen jako rozšíření aplikace POSTMAN do prohlížeče 
<a href="https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop" target="_blank">Chrome</a>).

**Příklad využití knihovny IdentityModel (s využitím Visual Studia)**
```

Install-Package IdentityModel

```
```
// Vstupní parametry pro zisk tokenu
var parameters = new ClientCredentialsTokenRequest
{
    Address = "https://vasefirma.labelprinter.cz/connect/token",
    Scope = "lp_api_full",
    ClientId = "client",
    ClientSecret = "secret",
    // Nastavte tento typ basic autentizace
    AuthorizationHeaderStyle = BasicAuthenticationHeaderStyle.Rfc2617,
    // Doporučujeme zadávat přístupové údaje v hlavičce (nikoliv v těle požadavku)
    ClientCredentialStyle = ClientCredentialStyle.AuthorizationHeader
};

// Zisk tokenu přes extension metodu třídy HttpClient (instanci doporučujeme získávat přes HttpClientFactory)
// (přístup přes instanci třídy TokenClient a jeho konstruktor je Obsolete)
var httpClient = new HttpClient();
var token = await httpClient.RequestClientCredentialsTokenAsync(parameters);

// Objekt pro vytvoření požadavku a nastavení Bearer tokenu
httpClient.SetBearerToken(token.AccessToken);

// Požadavek a json odpověď
var result = await httpClient.GetStringAsync("https://vasefirma.labelprinter.cz/shippers");
```

## Verzování
| Verze LP      | Popis                                                                                                                                                                                                                                                                                                         |
|:--------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `4.3.51.0`    | Rozšíření možnosti filtrování odběrných míst i podle id odběrného místa<br/>Zavedení uzlu `externalBarcode` pro vyplnění externích čísel balíků od přepravce (vhodné např. pro přepravce Zásilkovna, kde lze využít packetId k tisku etiket bez nutnosti vytváření nových zásilek v systému Zásilkovny        |
| `4.3.50.0`    | Přidání příznaku `singleItem` na zásilku, kterým lze ovlivnit způsob zpracování v klientské aplikaci                                                                                                                                                                                                          |
| `4.3.38.0`    | U zásilek se budou v `response` vracet i údaje o hodnotě zásilky a dobírce (`price`, `priceCurrency`, `cod`, `codCurrency`)<br/>Možnost do zásilky přidat `processUserExternalId`, dle kterého lze přiřadit zásilku k danému uživateli                                                                        |
| `4.3.35.0`    | Metoda `users/logonhistory/filter` vrací i informaci o úspěšnosti přihlášení / odhlášení                                                                                                                                                                                                                      |
| `4.3.25.0`    | Přidání získání seznamu kontrol zboží a seznam přihlášení / odhlášení uživatelů                                                                                                                                                                                                                               |
| `4.2.16.0`    | Přílohám je možné zadat počet kopií atributem `numberOfCopies`                                                                                                                                                                                                                                                |
| `4.1.9.0`     | Velikost atributu `expeditionNote` na objektu `shipment` rozšířen na `string(max)`                                                                                                                                                                                                                            |
| `4.1.8.0`     | Možnost stahování odběrných míst všech přepravců z databáze aplikace **Label Printer**<br/>Přidán příznak `isInClosingDay` na <a href="#shipment_parcel">balík</a>, zda-li je balík v závěrce a byly tak odeslány data k přepravci.                                                                           |
| `4.0.5.0`     | Trackování zásilek (nové metody pod url `tracking`)<br/>Metoda `shipments/search` doplněna o možnost vyhledávat podle seznamu id, pomocí kritéria `ids`.<br/>Informace o balíku (uzel `parcel`) doplněn o atributy `delivered`, `returned`, `detected` a `trackingUrl`                                        |
| `3.16.14.0`   | Oprava metody `shipments/search`, kde byl na vstupu uzel `history`<br/>Do `POST` metody `shipments/search` přidán parametr `includeHistory`, který v případě nastavení bude vracet i historii daného záznamu.                                                                                                 |
| `3.16.9.0`    | Možnost hledat zásilky podle změn atributů v určitém období pomocí uzlu `history` (např. změna stavu zásilek do stavu Tištěný v období dneška mezi 12:00 - 15:00 apod.)<br/>Možnost získat kompletní historii akcí, které se na dané zásilce, či zásilkách vyskytly pomocí query parametru `includeHistory`   |
| `3.16.1.0`    | Oprava práce s uzlem `trackingNumber` vrácený v sekci `parcels` (bude nyní vyplněn vždy po uložení a tisku etikety daného přepravce)<br/>Zavedení uzlu `mainBarcode` pro vyplnění čísel zásilek u přepravců, kteří využívají dvou čárových kódů na etiketě (např. PPL Sprint - Palety)                        |
| `3.15.22.0`   | Přidání uzlu pro vkládání příloh k zásilce (uzel `media`)                                                                                                                                                                                                                                                     |
| `3.15.21.0`   | Možnost využít pole `depotAddressCode` pro změnu označení eshopu (odesilatele) pro přepravce **Zásilkovna**                                                                                                                                                                                                   |
| `3.15.20.0`   | Přidání uzlu `messages` v `http` odpovědích pro zjištění případné chyby během tisku<br/>Oprava pro automatické doplňování doplňkových služeb přepravců                                                                                                                                                        |
| `3.15.19.0`   | Oprava validace zboží (uzel `goods`)                                                                                                                                                                                                                                                                          |
| `3.15.16.0`   | Přidání uzlů pro definici zboží v zásilce (uzel `goods`)                                                                                                                                                                                                                                                      |
| `3.15.9.0`    | Přidání parametru `codPaymentType` pro určení typu platby<br/>Přidání parametru `processUser` pro zadání uživatele, který má danou zásilku zracovávat                                                                                                                                                         |
| `3.14.0.0`    | Vznik **LP Api**                                                                                                                                                                                                                                                                                              |

## Group Přístupový token

Ke každému požadavku je vyžadován tzv. přístupový token, o který musíte zažádat na adrese 
`https://vasefirma.labelprinter.cz/connect/token`. Tento token pak budete vkládat do hlavičky konkrétních požadavků na `API`. 
Využíváme tzv. **bearer token**. Typ tokenu ovšem dostanete v odpovědi na přístupový token, takže při změně můžete zareagovat. 
V odpovědi rovněž dostanete čas v sekundách, který udává expiraci daného tokenu. Výchozí čas je nastaven na 30 minut (1800s). 
Abyste dostali v odpovědi přístupový token, je třeba zadat správné přístupové údaje (`client_id` a `client_secret`), které od nás po 
dohodě dostanete. Přístupové údaje lze zadávat v těle `POST` požadavku anebo zabezpečeně pomocí `Basic autentizace` v hlavičce `POST` požadavku. 
My doporučujeme citlivé přístupové údaje zasílat v hlavičce požadavku pomocí `Basic autentizace`. Poslední povinné údaje, které je nutné 
zadat do těla `POST` požadavku jsou parametry `grant_type` a `scope`. Hodnotu parametru `grant_type` nastavte na `client_credentials`. Hodnotu, kterou 
bude nutné zadat do parametru `scope` se dozvíte po dohodě s námi (společně s přístupovými údaji `client_id` a `client_secret`). `Content-Type` v hlavičce 
nastavte na formát `application/x-www-form-urlencoded`.

### API metody [/connect]
#### Žádost o přístupový token [POST /connect/token]

+ Request (application/x-www-form-urlencoded)
    + Headers

            Authorization: Basic ZGlhbW9uZDpEWW5BeUdHalpvQ283dXhsYjlQYU1SVDNtbGo3b0pIS3NBPT0=
            
    + Body

            {
               "grant_type": "client_credentials",
               "scope": "lp_api_full"
            }

+ Response 200 (application/json)

        {
            "access_token": "4d060bc068f44909c1375c6cd4b773a3",
            "expires_in": 1800,
            "token_type": "Bearer"
        }

## Group Zásilky

Zásilky lze v aplikaci **Label Printer** vytvářet samostatně bez nutnosti tisku etiket, o které si můžete zažádat až později přes klientskou aplikaci **Label Printer**. 
Pokud chcete tisknout rovnou přes `API`, tak je nutné vyplnit parametr `labels` v požadavku na uložení zásilky (metodou `POST`). Etiketa se vrátí v odpovědi `http` požadavku ve formátu base64 a taková zásilka bude ve stavu `Tištěný`.

> Pokud využíváte klientskou aplikaci **Label Printer** a nastane během tisku nějaká chyba (validační, chyba u daného přepravce apod.), lze důvod této chyby najít 
v uzlu `data[0].messages`. Prozatím rozlišujeme pouze typ s hodnotou `1`, která značí chybu. V budoucnu toto může být rozšířeno o další typy zpráv (informační, varovné apod.). 
Text zprávy (chyby) pak najdete v uzlu `data[0].messages[0].message`.

### Parametry

<a name="shipment_root"></a>
| Parametr                  | Typ                                               | Povinný   | Popis                                                                                                                                                                                                                                         |
|:--------------------------|---------------------------------------------------|-----------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `id`                      | integer                                           | Ne        | Jedinečný identifikátor v systému Label Printer (**při vytváření se ignoruje!**)                                                                                                                                                              |
| `processUser`             | string(200)                                       | Ne        | Specifikace uživatele (jeho **login**), kterému je zásilka určena                                                                                                                                                                             |
| `processUserExternalId`   | string(200)                                       | Ne        | Specifikace uživatele (jeho **externí id**), kterému je zásilka určena                                                                                                                                                                        |
| `shipmentDay`             | date                                              | Ne        | Datum podání (formát yyyy-MM-dd)                                                                                                                                                                                                              |
| `shipperCode`             | string(20)                                        | Ano       | Kód přepravce (CP, PPL, DPD, ...). Viz metoda pro zisk přepravců                                                                                                                                                                              |
| `serviceCode`             | string(50)                                        | Ano       | Kód přepravní služby (DR, NP, ...). Metoda pro zisk přepravců vrací i seznam služeb                                                                                                                                                           |
| `variableSymbol`          | string(10)                                        | Ano       | Variabilní symbol                                                                                                                                                                                                                             |
| `orderNumber`             | string(12)                                        | Ano       | Číslo objednávky                                                                                                                                                                                                                              |
| `paymentInAdvance`        | boolean                                           | Ne        | Platba předem                                                                                                                                                                                                                                 |
| `price`                   | decimal(13,4)                                     | Ano       | Cena zásilky                                                                                                                                                                                                                                  |
| `priceCurrency`           | string(3)                                         | Ano       | Měna zásilky v iso4217 formátu (např. CZK, EUR)                                                                                                                                                                                               |
| `cod`                     | decimal(13,4)                                     | Ne        | Cena dobírky                                                                                                                                                                                                                                  |
| `codCurrency`             | string(3)                                         | Ne        | Měna dobírky v iso4217 formátu (např. CZK, EUR)                                                                                                                                                                                               |
| `codBankAccount`          | string(50)                                        | Ne        | Bankovní účet, kam se má posílat vybraná dobírka (tvar 35-123457/0100)                                                                                                                                                                        |
| `codPaymentType`          | integer                                           | Ne        | Typ platby pro dobírku (0 = hotovost, 1 = kartou / šekem)                                                                                                                                                                                     |
| `customExternalId`        | string(100)                                       | Ne        | Externí označení zásilky                                                                                                                                                                                                                      |
| `depotAddressCode`        | string(50)                                        | Ne        | Kód adresy depa (možnost využít toto pole pro změnu označení eshopu pro přepravce **Zásilkovna**)                                                                                                                                             |
| `description`             | string(500)                                       | Ne        | Popis                                                                                                                                                                                                                                         |
| `personalCollection`      | boolean                                           | Ne        | Osobní odběr                                                                                                                                                                                                                                  |
| `singleItem`              | boolean                                           | Ne        | Jednokusová zásilka (ovlivňuje způsob zpracování v klientské apliaci)                                                                                                                                                                         |
| `deliveryPointId`         | string(20)                                        | Ne        | Id odběrného místa                                                                                                                                                                                                                            |
| `expeditionNote`          | string(max)                                       | Ne        | Poznámka expedice                                                                                                                                                                                                                             |
| `paletteManipulationType` | string(20)                                        | Ne        | Typ manipulace v případě paletové přepravy                                                                                                                                                                                                    |
| `palettePickupType`       | string(20)                                        | Ne        | Typ svozu v případě paletové přepravy                                                                                                                                                                                                         |
| `textOnExtendedLabel`     | string(200)                                       | Ne        | Text, který se bude tisknout na rozšířenou etiketu (takovou, která má větší výšku než klasická A6 (105 x 148), tedy vyšší velikost než 148 mm). Jedná se pouze i přímý tisk na tiskárnu, přes API se taková etiketa v base64 vracet nebude)   |
| `additionalServices`      | string array                                      | Ne        | Pole string hodnot, které označují vybrané doplňkové služby dané přepravní služby                                                                                                                                                             |
| `recipient`               | <a href="#shipment_recipient">object</a>          | Ano       | Příjemce a informace o něm                                                                                                                                                                                                                    |
| `preferredSender`         | <a href="#shipment_preferredSender">object</a>    | Ne        | Preferovaný odesilatel (nevyplňujte v případě, že využíváte odesilatele registrovaného v systému Label Printer)                                                                                                                               |
| `parcels`                 | <a href="#shipment_parcel">object array</a>       | Ano       | Pole objektů typu parcel, ve kterém jsou uložené informace o balíku v dané zásilce. Délka pole určuje počet balíků pro danou zásilku. Minimální počet je 1.                                                                                   |
| `goods`                   | <a href="#shipment_goods">object array</a>        | Ne        | Pole objektů typu goods, ve kterém jsou uložené informace o zboží v dané zásilce.                                                                                                                                                             |
| `media`                   | <a href="#shipment_media">object array</a>        | Ne        | Pole objektů typu media, ve kterém jsou uložené přílohy k zásilce (např. faktury, návody apod.)                                                                                                                                               |
| `labels`                  | <a href="#shipment_label">object</a>              | Ne        | Definice vlastností pro vrácení štítků.                                                                                                                                                                                                       |

<a name="shipment_recipient"></a>
####Příjemce (recipient)
| Parametr      | Typ           | Povinný   | Popis                                                 |
|:--------------|---------------|-----------|-------------------------------------------------------|
| `company`     | string(200)   | Ano       | Název firmy nebo osoby                                |
| `person`      | string(200)   | Ne        | Osobní kontakt                                        |
| `street`      | string(100)   | Ano       | Adresa (Ulice, číslo popisné i orientační)            |
| `street2`     | string(100)   | Ne        | Doplnění adresy                                       |
| `city`        | string(50)    | Ano       | Město                                                 |
| `postalCode`  | string(10)    | Ano       | PSČ                                                   |
| `countryCode` | string(2)     | Ano       | Kód státu v ISO 3166-1 alpha-2 formátu (např. CZ, SK) |
| `ico`         | string(15)    | Ne        | Ičo                                                   |
| `phone`       | string(20)    | Ne        | Telefon                                               |
| `email`       | string(200)   | Ne        | Email                                                 |

<a name="shipment_preferredSender"></a>
####Preferovaný odesilatel (preferredSender)
| Parametr      | Typ               | Povinný   | Popis                                                 |
|:--------------|-------------------|-----------|-------------------------------------------------------|
| `company`     | string(200)       | Ano       | Název firmy nebo osoby                                |
| `street`      | string(100)       | Ano       | Adresa (Ulice, číslo popisné i orientační)            |
| `city`        | string(50)        | Ano       | Město                                                 |
| `postalCode`  | string(10)        | Ano       | PSČ                                                   |
| `countryCode` | string(2)         | Ano       | Kód státu v ISO 3166-1 alpha-2 formátu (např. CZ, SK) |
| `phone`       | string(20)        | Ne        | Telefon                                               |
| `email`       | string(200)       | Ne        | Email                                                 |
| `logo`        | varbinary(max)    | Ne        | Logo (base64)                                         |

<a name="shipment_parcel"></a>
####Balík (parcel)
| Parametr          | Typ               | Povinný   | Popis                                                                                                                                                         |
|:------------------|-------------------|-----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `barcode`         | string(50)        | Ne        | Číslo balíku (čárový kód)                                                                                                                                     |
| `mainBarcode`     | string(50)        | Ne        | Hlavní číslo zásilky (vyplňuje se v případě využití dvou čárových kódů (např. PPL Sprint - Palety))                                                           |
| `externalBarcode` | string(50)        | Ne        | Externí číslo balíku (např. pro přepravce Zásilkovna lze tímto nastavit packetId, které LP převezme a již nevytváří zásilku v Zásilkovně - pouze se tiskne etiketa) |
| `trackingNumber`  | string(50)        | Ne        | Sledovací číslo                                                                                                                                               |
| `trackingUrl`     | string(500)       | Ne        | Adresa pro sledování zásilky na webu přepravce                                                                                                                |
| `weight`          | decimal(13,4)     | Ne        | Váha (v kilogramech)                                                                                                                                          |
| `width`           | decimal(13,4)     | Ne        | Šířka (v centimetrech)                                                                                                                                        |
| `height`          | decimal(13,4)     | Ne        | Výška (v centimetrech)                                                                                                                                        |
| `depth`           | decimal(13,4)     | Ne        | Délka / hloubka (v centimetrech)                                                                                                                              |
| `volume`          | decimal(13,4)     | Ne        | Objem (v litrech)                                                                                                                                             |
| `wrapCode`        | string(20)        | Ne        | Obal                                                                                                                                                          |
| `delivered`       | datetime          | Ne        | Datum a čas doručení balíku příjemci (informace ze systému přepravce, formát yyyy-MM-dd HH:mm:ss)                                                             |
| `returned`        | datetime          | Ne        | Datum a čas vrácení balíku odesílateli (informace ze systému přepravce, formát yyyy-MM-dd HH:mm:ss)                                                           |
| `detected`        | datetime          | Ne        | Datum a čas zjištění stavu doručení / vrácení balíku (formát yyyy-MM-dd HH:mm:ss)                                                                             |
| `isInClosingDay`  | boolean           | Ne        | Příznak, zda-li je balík v závěrce (prošel akcí Uzávěrka dne a odeslaly se tak data přepravci)                                                                |

<a name="shipment_goods"></a>
####Zboží (goods)
| Parametr          | Typ                                                   | Povinný   | Popis                                                                                 |
|:------------------|-------------------------------------------------------|-----------|---------------------------------------------------------------------------------------|
| `name`            | string(200)                                           | Ne        | Název zboží                                                                           |
| `barcode`         | string(50)                                            | Ano       | Čárový kód (EAN apod.)                                                                |
| `location`        | string(100)                                           | Ne        | Umístění (na skladě)                                                                  |
| `quantity`        | decimal(13,4)                                         | Ano       | Množství                                                                              |
| `ratio`           | decimal(13,4)                                         | Ne        | Poměr k jednomu kusu daného zboží (pokud neuvedete, výchozí je 1)                     |
| `unitCode`        | string(10)                                            | Ano       | Jednotka zboží (např. ks, paleta, cm3)                                                |
| `unitPrice`       | decimal(13,4)                                         | Ne        | Jednotková cena                                                                       |
| `currencyCode`    | string(3)                                             | Ne        | Měna zásilky v iso4217 formátu (např. CZK, EUR)                                       |
| `naftaTariffCode` | string(50)                                            | Ne        | Celní kód                                                                             |
| `countryCode`     | string(2)                                             | Ne        | Země původu v ISO 3166-1 alpha-2 formátu (např. CZ, SK)                                 |
| `alternatives`    | <a href="#shipment_goodsAlternative">object array</a> | Ne        | Možné alternativy ke zboží (jiné čárové kódy stejného zboží, vícekusové balení atd.)  |

<a name="shipment_goodsAlternative"></a>
####Zboží - Alternativy (goodsAlternative)
| Parametr      | Typ               | Povinný   | Popis                                                                                                                                                                     |
|:--------------|-------------------|-----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `name`        | string(200)       | Ne        | Alternativní název zboží (pokud je jiný než je uveden v objektu goods)                                                                                                    |
| `barcode`     | string(50)        | Ano       | Čárový kód (EAN apod.)                                                                                                                                                    |
| `location`    | string(100)       | Ne        | Umístění (na skladě)                                                                                                                                                      |
| `ratio`       | decimal(13,4)     | Ne        | Vztah k základní jednotce (např. uvedete-li hodnotu 10, znamená to, že dané balení je po 10ti kusech (za předpokladu, že základní jednotka je kus a základní poměr je 1)) |

<a name="shipment_media"></a>
####Přílohy (media)
| Parametr          | Typ               | Povinný   | Popis                                             |
|:------------------|-------------------|-----------|---------------------------------------------------|
| `mediaType`       | integer           | Ano       | Typ souboru (1 = Faktura)                         |
| `fileName`        | string(256)       | Ano       | Název souboru i s příponou (např. faktura.pdf)    |
| `numberOfCopies`  | integer           | Ne        | Počet kopií                                       |
| `data`            | string(max)       | Ano       | Obsah souboru v base64                            |

<a name="shipment_label"></a>
####Štítek (label)
| Parametr      | Typ               | Povinný   | Popis                             |
|:--------------|-------------------|-----------|-----------------------------------|
| `format`      | string(2)         | Ano       | Formát štítku (A4, A6)            |

### API metody [/shipments]

#### Detail zásilky [GET /shipments/{id}/{?includeHistory}]

+ Parameters
    + id (Integer) - Identifikátor zásilky v systému Label Printer
    + includeHistory (optional, bool) - Výsledek vrátit včetně historie (povolené hodnoty true/false)
    
+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [
            {
                "id": 1206,
                "variableSymbol": "123",
                "orderNumber": "456",
                "customExternalId": "EX-41",
                "shipmentDay": "2018-09-03",
                "startProcessing": "2018-09-03 13:40:13",
                "printedAt": "2018-09-03 13:41:57",
                "shipper": "CP",
                "shipperService": "DR",
                "deliveryPointId": null,
                "expeditionNote": "Poznámka expedice",
                "singleItem": false,
                "state": {
                    "code": 1,
                    "name": "Netištěný"
                },
                "parcels": [
                    {
                        "barcode": "DR9027000448C",
                        "mainBarcode": null,
                        "externalBarcode": null,
                        "trackingNumber": "DR9027000448C",
                        "trackingUrl": "https://www.postaonline.cz/trackandtrace/-/zasilka/cislo?parcelNumbers=DR9027000448C",
                        "weight": 4.5,
                        "width": null,
                        "height": null,
                        "depth": null,
                        "volume": null,
                        "wrapCode": null,
                        "delivered": null,
                        "returned": null,
                        "detected": null,
                        "isInClosingDay": true
                    },
                    {
                        "barcode": "DR9027000451C",
                        "mainBarcode": null,
                        "externalBarcode": null,
                        "trackingNumber": "DR9027000451C",
                        "trackingUrl": "https://www.postaonline.cz/trackandtrace/-/zasilka/cislo?parcelNumbers=DR9027000451C",
                        "weight": 1.2,
                        "width": null,
                        "height": null,
                        "depth": null,
                        "volume": null,
                        "wrapCode": null,
                        "delivered": null,
                        "returned": null,
                        "detected": null,
                        "isInClosingDay": true
                    }
                ],
                "history": [
                    {
                      "linkCode": "shipment",
                      "user": "Admin",
                      "userExternalId": "Admin123",
                      "created": "2019-08-12 12:35",
                      "items": [
                        {
                          "property": "Stav",
                          "oldValue": "Netištěný",
                          "newValue": "Tištěný"
                        },
                        {
                          "property": "Tištěno na PC",
                          "oldValue": null,
                          "newValue": "VOJTA"
                        }
                      ]
                    }
                ],
                "labels": null,
                "messages": [
                    {
                        "type": 1,
                        "message": "Není vyplněna adresa odesilatele."
                    }
                ]
            }],
            "errors": []
        }

#### Vyhledání zásilek [POST /shipments/search]
<a name="shipment_search"></a>
Vyhledávání zásilek probíhá metodou `POST` na adrese `/shipments/search` (viz příklad). Vstupem je `json`, do kterého se zadávájí vyhledávácí 
kritéria, podle kterých systém **Label Printer** vyhledá zásilky a vrátí ve standardním formátu. Kritéria `shipmentDayFrom` a `shipmentDayTo` 
se zadávají ve formátu `yyyy-MM-dd`. Ostatní kritéria se zadávájí klasickým polem string hodnot. V případě zadání kritéria `id` nebo `ids` se jedná o integer hodnotu, potažmo pole integer hodnot.

Pokud chcete vrátit výsledek hledání včetně historie akcí, pak musíte nastavit parametr `includeHistory`. Tento parametr je kritický na výkon, takže radíme využívat pouze na omezenou množinu možných vrácených záznamů popř. využívat v `GET` metodě 
pro vrácení detailu zásilky.

Pokud chcete jen dle historie záznamů vyhledávat, pak nastavte uzel `history`. Ten využívá parametry `linkCode`, který v případě 
zásilek musí být nastaven na hodnotu **shipment**. Pokud hodnotu **shipment** neuvedete, aplikace **Label Printer** ji doplní za vás. Parametry `from` a 
`to` určují rozmezí, kdy se daná změna udála. Parametr `column` určuje, u kterého atributu nás změna zajímá (jakých může nabývat hodnot najdete <a href="#history_columns">zde</a>). 
Parametrem `oldValue` určíme, z které hodnoty se změna prováděla a parametrem `newValue`, na kterou hodnotu se změnila.


+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3
                
    + Body
    
            {
              "id": null,
              "ids": [],
              "variableSymbols": [ "123", "456", "789" ],
              "orderNumbers": [],
              "shipmentDayFrom": "2018-09-01",
              "shipmentDayTo": "2018-09-05",
              "barcodes": [],
              "customExternalIds": [],
              "includeHistory": true,
              "history": {
                "linkCode": "shipment",
                "from": "2019-08-12 12:00",
                "to": "2019-08-12 15:00",
                "column": "fk_shipment_state",
                "oldValue": null,
                "newValue": "2"
              }
            }

+ Response 200 (application/json)

    + Body

            {
                "code": 200,
                "data": [
                    {
                        "id": 1206,
                        "variableSymbol": "123",
                        "orderNumber": "456",
                        "customExternalId": "EX-41",
                        "expeditionNote": "Poznámka expedice",
                        "shipmentDay": "2018-09-03",
                        "startProcessing": "2018-09-03 13:40:13",
                        "printedAt": "2018-09-03 13:41:57",
                        "shipper": "CP",
                        "shipperService": "DR",
                        "deliveryPointId": null,
                        "price": 1691.0000,
                        "priceCurrency": "CZK",
                        "cod": null,
                        "codCurrency": null,
                        "state": {
                            "code": 1,
                            "name": "Netištěný"
                        },
                        "parcels": [
                            {
                                "barcode": "DR9027000448C",
                                "mainBarcode": null,
                                "externalBarcode": null,
                                "trackingNumber": "DR9027000448C",
                                "trackingUrl": "https://www.postaonline.cz/trackandtrace/-/zasilka/cislo?parcelNumbers=DR9027000448C",
                                "weight": 4.5,
                                "width": null,
                                "height": null,
                                "depth": null,
                                "volume": null,
                                "wrapCode": null,
                                "delivered": null,
                                "returned": null,
                                "detected": null,
                                "isInClosingDay": true
                            },
                            {
                                "barcode": "DR9027000451C",
                                "mainBarcode": null,
                                "externalBarcode": null,
                                "trackingNumber": "DR9027000451C",
                                "trackingUrl": "https://www.postaonline.cz/trackandtrace/-/zasilka/cislo?parcelNumbers=DR9027000451C"
                                "weight": 3.4,
                                "width": null,
                                "height": null,
                                "depth": null,
                                "volume": null,
                                "wrapCode": null,
                                "delivered": null,
                                "returned": null,
                                "detected": null,
                                "isInClosingDay": true
                            }
                        ],
                        "history": [
                            {
                              "linkCode": "shipment",
                              "user": "Admin",
                              "userExternalId": "Admin123",
                              "created": "2019-08-12 12:35",
                              "items": [
                                {
                                  "property": "Stav",
                                  "oldValue": "Netištěný",
                                  "newValue": "Tištěný"
                                },
                                {
                                  "property": "Tištěno na PC",
                                  "oldValue": null,
                                  "newValue": "VOJTA"
                                }
                              ]
                            }
                        ],
                        "labels": null,
                        "messages": [
                            {
                                "type": 1,
                                "message": "Není vyplněna adresa odesilatele."
                            }
                        ]
                    }
                ],
                "errors": []
            }

#### Vytvoření zásilky [POST]

+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3
                
    + Body
    
            {
              "id": null,
              "processUser": "expedice1",
              "processUserExternalId": "externí id uživatele",
              "shipperCode": "CP",
              "serviceCode": "DR",
              "variableSymbol": "123",
              "orderNumber": "456",
              "paymenrrInAdvance": false,
              "price": 560.0,
              "priceCurrency": "CZK",
              "cod": 560.45,
              "codCurrency": "CZK",
              "codBankAccount": "35-123457/0100",
              "codPaymentType": "1",
              "customExternalId": "FiremníId",
              "depotAddressCode": null,
              "description": "Popis",
              "personalCollection": false,
              "deliveryPointId": null,
              "singleItem": false,
              "expeditionNote": "Poznámka expedice",
              "paletteManipulationType": null,
              "palettePickupType": null,
              "textOnExtendedLabel": "TEXT NA ROZŠÍŘENÉ ETIKETĚ"
              "additionalServices": [ "41", "45" ],
              "recipient": {
                "company": "Diamond Software s.r.o.",
                "person": "Tomáš Novák",
                "street": "Uliční 45",
                "street2": null,
                "city": "Ostrava",
                "postalCode": "70200",
                "countryCode": "CZ",
                "phone": "+420603223344",
                "email": "email@email.cz",
                "ico": null
              },
              "preferredSender": null,
              "parcels": [
                {
                  "barcode": null,
                  "weight": 4.5,
                  "width": null,
                  "height": null,
                  "depth": null,
                  "volume": null,
                  "wrapCode": null
                },
                {
                  "barcode": null,
                  "weight": 3.4,
                  "width": null,
                  "height": null,
                  "depth": null,
                  "volume": null,
                  "wrapCode": null
                }
              ],
              "goods": [
                {
                  "name": "Kartáček",
                  "barcode": "69745123694",
                  "location": "A3",
                  "quantity": 1,
                  "ratio": 1,
                  "unitCode": "ks",
                  "unitPrice": 120.00,
                  "currencyCode": "CZK",
                  "naftaTariffCode": "85071020",
                  "countryCode": "CZ",
                  "alternatives": [
                    {
                      "name": "Kartáček 2v1",
                      "barcode": "57455432567",
                      "location": "A4",
                      "ratio": 2
                    },
                    {
                      "name": "10 kartáčků",
                      "barcode": "68734364687",
                      "location": "B1",
                      "ratio": 10
                    }
                  ]
                }
              ],
              "media": [
                    {
                        "mediaType": 1,
                        "fileName": "faktura.pdf",
                        "data": "content_in_base64_format"
                    }
              ],
              "labels": {
                  "format": "A6"
              }
            }

+ Response 201 (application/json)

    + Body

            {
                "code": 200,
                "data": [
                    {
                        "id": 1206,
                        "variableSymbol": "123",
                        "orderNumber": "456",
                        "customExternalId": "EX-41",
                        "expeditionNote": null,
                        "shipmentDay": "2018-09-03",
                        "startProcessing": "2018-09-03 13:40:13",
                        "printedAt": "2018-09-03 13:41:57",
                        "shipper": "CP",
                        "shipperService": "DR",
                        "deliveryPointId": null,
                        "price": 1691.0000,
                        "priceCurrency": "CZK",
                        "cod": null,
                        "codCurrency": null,
                        "state": {
                            "code": 1,
                            "name": "Netištěný",
                            "messages": null
                        },
                        "parcels": [
                            {
                                "barcode": "DR9027000448C",
                                "mainBarcode": null,
                                "externalBarcode": null,
                                "trackingNumber": "DR9027000448C",
                                "weight": 4.5,
                                "width": null,
                                "height": null,
                                "depth": null,
                                "volume": null,
                                "wrapCode": null,
                                "trackingNumber": null,
                                "trackingUrl": null,
                                "delivered": null,
                                "returned": null,
                                "detected": null,
                                "isInClosingDay": false
                            },
                            {
                                "barcode": "DR9027000451C",
                                "mainBarcode": null,
                                "externalBarcode": null,
                                "trackingNumber": "DR9027000451C",
                                "weight": 3.4,
                                "width": null,
                                "height": null,
                                "depth": null,
                                "volume": null,
                                "wrapCode": null,
                                "trackingNumber": null,
                                "trackingUrl": null,
                                "delivered": null,
                                "returned": null,
                                "detected": null,
                                "isInClosingDay": false
                            }
                        ],
                        "labels": null,
                        "messages": [
                            {
                                "type": 1,
                                "message": "Není vyplněna adresa odesilatele."
                            }
                        ]
                    }
                ],
                "errors": []
            }
            
#### Storno zásilky [DELETE /shipments/{id}]
Zásilky lze v systému **Label Printer** stornovat (změnit stav zásilky na Stornovaný s kódem 3). Tyto zásilky pak nelze uzavřít a tudíž 
nejdou data daných zásilek do systémů daných přepravců. Buďte ovšem s touto funkcí opatrní a používejte ji jen v situacích, kdy jste si 
stornem zásilky naprosto jisti.

+ Parameters
    + id (Integer) - Identifikátor zásilky v systému Label Printer
    
+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [],
            "errors": []
        }
          
## Group Trackování zásilek
Trackovat lze jednu zásilku `GET` metodou dle předaného id anebo lze získat trackovací informace pro více zásilek najednou přes `POST` 
metodu s předným filtrem v těle `http` požadavku.
            
### Parametry

<a name="tracking_root"></a>
| Parametr                  | Typ                                               | Povinný   | Popis                                                                                                             |
|:--------------------------|---------------------------------------------------|-----------|-------------------------------------------------------------------------------------------------------------------|
| `shipmentId`              | integer                                           | Ne        | Jedinečný identifikátor zásilky v systému Label Printer.                                                          |
| `variableSymbol`          | string(10)                                        | Ano       | Variabilní symbol zásilky                                                                                         |
| `orderNumber`             | string(12)                                        | Ano       | Číslo objednávky zásilky                                                                                          |
| `customExternalId`        | string(100)                                       | Ne        | Externí označení zásilky                                                                                          |
| `shipmentDay`             | date                                              | Ano       | Datum podání (formát yyyy-MM-dd)                                                                                  |
| `printedAt`               | datetime                                          | Ne        | Datum a čas tisku etiket (formát yyyy-MM-dd HH:mm:ss)                                                             |
| `barcode`                 | string(50)                                        | Ne        | Číslo balíku (čárový kód)                                                                                         |
| `mainBarcode`             | string(50)                                        | Ne        | Hlavní číslo zásilky (vyplňuje se v případě využití dvou čárových kódů (např. PPL Sprint - Palety))               |
| `trackingNumber`          | string(50)                                        | Ne        | Sledovací číslo                                                                                                   |
| `shipperCode`             | string(20)                                        | Ano       | Kód přepravce (CP, PPL, DPD, ...). Viz metoda pro zisk přepravců                                                  |
| `serviceCode`             | string(10)                                        | Ano       | Kód přepravní služby (DR, NP, ...). Metoda pro zisk přepravců vrací i seznam služeb                               |
| `weight`                  | decimal(13,4)                                     | Ne        | Váha balíku nebo celé zásilky                                                                                     |
| `storedIn`                | datetime                                          | Ne        | Datum a čas, do kdy je zásilka uložena na depu (využívá ČP, formát yyyy-MM-dd HH:mm:ss)                           |
| `trackingUrl`             | string(1000)                                      | Ne        | Trackovací url                                                                                                    |           
| `trackingItems`           | <a href="#trackingItem">object array</a>          | Ne        | Pole objektů typu trackingItem, ve kterém jsou uložené všechny informace o trackování balíku                      |

<a name="trackingItem"></a>
####Trackovací informace (trackingItem)
| Parametr          | Typ           | Povinný   | Popis                                                 |
|:------------------|---------------|-----------|-------------------------------------------------------|
| `date`            | datetime      | Ano       | Datum a čas události (formát yyyy-MM-dd HH:mm:ss)     |
| `description`     | string(500)   | Ne        | Popis událost                                         |
| `postalCode`      | string(20)    | Ano       | PSČ depa, kde se událost provedla                     |
| `placeOfEvent`    | string(100)   | Ne        | Místo vzniku události                                 |
            
### API metody [/tracking]

#### Trackování jedné zásilky [GET /tracking/{id}]
Pokud zásilka má více balíků, v `http` odpovědi se vrátí trackovací informace všech balíků.

+ Parameters
    + id (Integer) - Identifikátor zásilky v systému Label Printer
    
+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [
                {
                    "shipmentId": 1061,
                    "variableSymbol": "1",
                    "orderNumber": "1",
                    "customExternalId": null,
                    "shipmentDay": "2020-02-07",
                    "printedAt": "2020-02-07 15:04:10",
                    "barcode": "0000000009*101",
                    "mainBarcode": null,
                    "trackingNumber": "0000000009",
                    "shipperCode": "FOFR",
                    "serviceCode": "B",
                    "weight": 0.00,
                    "storedIn": null,
                    "trackingUrl": "https://objednavky.fofrcz.cz/index.php?id=sledovani&rok=2020&shipment_num=0000000009",
                    "trackingItems": [
                        {
                            "date": "2020-02-20 00:00:00",
                            "description": "Čeká se na přenos dat",
                            "postalCode": null,
                            "placeOfEvent": "CP"
                        }
                    ]
                }
            ],
            "errors": []
        }

#### Trackování více zásilek [POST /tracking]
Trackovat lze více zásilek najednou pomocí vstupního filtru metodou `POST` v těle `http` požadavku. Někteří přepravci mohou generovat po určité době 
stejné trackovací čísla (nebo čísla balíků atd.), proto je dobré množinu vrácených informací omezit např. rozmezím dat (parametry `shipmentDayFrom` a `shipmentDayTo`). 
Např. Česká Pošta umožňuje stejné čísla po 13 měsících.

+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3
                
    + Body
    
            {
              "id": null,
              "variableSymbols": [],
              "orderNumbers": [],
              "customExternalIds": [],
              "shipmentDayFrom": "2020-01-01",
              "shipmentDayTo": "2020-12-31",
              "barcodes": [],
              "trackingNumbers": [ "DR3601000062C", "DR3601000080C" ]
            }

+ Response 200 (application/json)

    + Body

            {
                "code": 200,
                "data": [
                    {
                        "shipmentId": 1053,
                        "variableSymbol": "1",
                        "orderNumber": "ZAK24",
                        "customExternalId": "",
                        "shipmentDay": "2020-01-10",
                        "printedAt": "2020-01-10 16:22:03",
                        "barcode": "DR3601000080C",
                        "mainBarcode": null,
                        "trackingNumber": "DR3601000080C",
                        "shipperCode": "CP",
                        "serviceCode": "DR",
                        "weight": 0.0,
                        "storedIn": null,
                        "trackingUrl": "https://www.postaonline.cz/cs/trackandtrace/-/zasilka/cislo?parcelNumbers=DR3601000080C",
                        "trackingItems": [
                            {
                                "date": "2019-07-08 00:00:00",
                                "description": "Vrácení zásilky odesílateli.",
                                "postalCode": "74207",
                                "placeOfEvent": "Depo Nový Jičín 70"
                            },
                            {
                                "date": "2019-07-08 00:00:00",
                                "description": "Doručování zásilky.",
                                "postalCode": "74207",
                                "placeOfEvent": "Depo Nový Jičín 70"
                            },
                            {
                                "date": "2019-07-08 00:00:00",
                                "description": "Příprava zásilky k doručení.",
                                "postalCode": "74207",
                                "placeOfEvent": "Depo Nový Jičín 70"
                            },
                            {
                                "date": "2019-07-04 00:00:00",
                                "description": "Přeprava zásilky k dodací poště.",
                                "postalCode": "",
                                "placeOfEvent": ""
                            },
                            {
                                "date": "2019-07-04 00:00:00",
                                "description": "Zásilka vypravena z třídícího centra.",
                                "postalCode": "22200",
                                "placeOfEvent": "SPU Praha 022"
                            },
                            {
                                "date": "2019-07-02 00:00:00",
                                "description": "Zásilka v přepravě.",
                                "postalCode": "",
                                "placeOfEvent": ""
                            },
                            {
                                "date": "2019-07-02 00:00:00",
                                "description": "Zásilka převzata do přepravy.",
                                "postalCode": "74207",
                                "placeOfEvent": "Depo Nový Jičín 70"
                            }
                        ]
                    },
                    {
                        "shipmentId": 1051,
                        "variableSymbol": "1",
                        "orderNumber": "ZAK22",
                        "customExternalId": "",
                        "shipmentDay": "2020-01-10",
                        "printedAt": "2020-01-10 16:11:31",
                        "barcode": "DR3601000062C",
                        "mainBarcode": null,
                        "trackingNumber": "DR3601000062C",
                        "shipperCode": "CP",
                        "serviceCode": "DR",
                        "weight": 0.0,
                        "storedIn": null,
                        "trackingUrl": "https://www.postaonline.cz/cs/trackandtrace/-/zasilka/cislo?parcelNumbers=DR3601000062C",
                        "trackingItems": [
                            {
                                "date": "2019-07-12 00:00:00",
                                "description": "Vrácení zásilky odesílateli.",
                                "postalCode": "74207",
                                "placeOfEvent": "Depo Nový Jičín 70"
                            },
                            {
                                "date": "2019-07-12 00:00:00",
                                "description": "Doručování zásilky.",
                                "postalCode": "74207",
                                "placeOfEvent": "Depo Nový Jičín 70"
                            },
                            {
                                "date": "2019-07-12 00:00:00",
                                "description": "Příprava zásilky k doručení.",
                                "postalCode": "74207",
                                "placeOfEvent": "Depo Nový Jičín 70"
                            },
                            {
                                "date": "2019-07-11 00:00:00",
                                "description": "Odeslání zásilky zpět odesílateli - nepředána data z podání.",
                                "postalCode": "17704",
                                "placeOfEvent": "Depo Praha 704"
                            },
                            {
                                "date": "2019-07-11 00:00:00",
                                "order": 0,
                                "description": "Přeprava zásilky k dodací poště.",
                                "postalCode": "",
                                "placeOfEvent": ""
                            },
                            {
                                "date": "2019-07-11 00:00:00",
                                "description": "Zásilka vypravena z třídícího centra.",
                                "postalCode": "22200",
                                "placeOfEvent": "SPU Praha 022"
                            },
                            {
                                "date": "2019-07-02 00:00:00",
                                "description": "Zásilka v přepravě.",
                                "postalCode": "",
                                "placeOfEvent": ""
                            },
                            {
                                "date": "2019-07-02 00:00:00",
                                "description": "Zásilka převzata do přepravy.",
                                "postalCode": "74207",
                                "placeOfEvent": "Depo Nový Jičín 70"
                            }
                        ]
                    }
                ],
                "errors": []
            }
            
## Group Stavy zásilek
V systému **Label Printer** se nastavují stavy zásilek automaticky podle příslušných akcí na dané zásilce (vytvoření zásilky, tisk etikety, 
storno zásilek apod.). Zásilky mohou být v následujících stavech.

> V odpovědi lze rovněž získat informaci o případné chybě, která mohla nastat např. během tisku přepravní etikety. Jedná se o stejný uzel, který 
lze dostat i v odpovědi při práci se zásilkami (viz uzel `data[0].messages`).

| Kód  | Název              | Popis                                                                                                     |
|:-----|--------------------|-----------------------------------------------------------------------------------------------------------|
| `1`  | Netištěný          | Zásilky, jejíž štítek ještě nebyl tištěn.                                                                 |
| `2`  | Tištěný            | Zásilky, jejíž štítek již byl vytištěn.                                                                   |
| `3`  | Stornovaný         | Zásilky, jenž byly stornovány. Po následné obnově dojde ke změně stavu na Netištěný.                      |
| `4`  | Připravený         | Zásilky, uložené do systému, ale nezpracované uživatelem.                                                 |
| `5`  | Nenačtený          | Zásilky, jejíž XML se nepodařilo načíst do systému.                                                       |
| `6`  | Spojený            | Zásilky, které byly spojeny do jiné zásilky.                                                              |
| `7`  | Tištěný s chybou   | Zásilky, jejíž štítek již byl vytištěn, ale obsahuje chybu a je nutné je prověřit a případně přetisknout. |

### API metody [/shipments/{id}/state]

#### Stav zásilky [GET /shipments/{id}/state]

+ Parameters
    + id (Integer) - Identifikátor zásilky v systému Label Printer
    
+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [
                {
                    "code": 2,
                    "name": "Tištěný",
                    "messages": [
                        {
                            "type": 1,
                            "message": "Není vyplněna adresa odesilatele."
                        }
                        ]
                }
            ],
            "errors": []
        }

## Group Kontrola zásilek
V systému **Label Printer** se kontrola zásilek provádí před tiskem etiket, kde skladník provádí kontrolu zboží, které expeduje zákazníkovi. 

<a name="goodsCheckingState"></a>
####Stav kontroly (goodsCheckingState)
| Kód   | Typ       | Popis                     |
|:------|-----------|---------------------------|
| `0`   | integer   | Nezkontrolováno           |
| `1`   | integer   | Částečně zkontrolováno    |
| `2`   | integer   | Plně s novými položkami   |
| `3`   | integer   | Plně zkontrolováno        |

### API metody [/goodscheckings]

#### Seznam kontrol [GET /goodscheckings/{shipmentId}]

+ Parameters
    + shipmentId (Integer) - Identifikátor zásilky v systému Label Printer
    
+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [
                {
                    "id": 19,
                    "shipmentId": 117764,
                    "user": "Vojtěc Hernas",
                    "userExternalId": 1023,
                    "from": "2023-02-10 09:18:17",
                    "to": "2023-02-10 09:19:06",
                    "duration": "00:00:48",
                    "description": null,
                    "pcName": "VOJTUVDELL",
                    "state": 3,
                    "stateFormat": "Plně",
                    "items": [
                        {
                            "id": 17,
                            "goods": {
                                "barcode": "AM0520",
                                "name": "Li-Pol baterie 60mAh, 3.7V, 401215",
                                "location": "",
                                "ratio": 1.0000,
                                "quantity": 1.0000,
                                "unitCode": "ks",
                                "unitPrice": 128.9300,
                                "currencyCode": "CZK",
                                "naftaTarifCode": null,
                                "countryCode": "CZ",
                                "alternatives": []
                            },
                            "goodsId": 247150,
                            "name": "Li-Pol baterie 60mAh, 3.7V, 401215",
                            "quantity": 1.0000,
                            "quantityFormat": "1 ks",
                            "sumQuantity": 1.00000000,
                            "sumQuantityFormat": "1 ks",
                            "unitCode": "ks",
                            "state": 3,
                            "stateFormat": "Plně",
                            "foundItems": [
                                {
                                    "id": 20,
                                    "barcode": "AM0520",
                                    "quantity": 1.0000,
                                    "ratio": 1.0000
                                }
                            ]
                        }
                    ]
                },
                {
                    "id": 18,
                    "shipmentId": 117764,
                    "user": "Vojtěc Hernas",
                    "userExternalId": 1023,
                    "from": "2023-02-10 09:17:01",
                    "to": "2023-02-10 09:18:05",
                    "duration": "00:01:04",
                    "description": null,
                    "pcName": "VOJTUVDELL",
                    "state": 3,
                    "stateFormat": "Plně",
                    "items": [
                        {
                            "id": 16,
                            "goods": {
                                "barcode": "AM0520",
                                "name": "Li-Pol baterie 60mAh, 3.7V, 401215",
                                "location": "",
                                "ratio": 1.0000,
                                "quantity": 1.0000,
                                "unitCode": "ks",
                                "unitPrice": 128.9300,
                                "currencyCode": "CZK",
                                "naftaTarifCode": null,
                                "countryCode": "CZ",
                                "alternatives": []
                            },
                            "goodsId": 247150,
                            "name": "Li-Pol baterie 60mAh, 3.7V, 401215",
                            "quantity": 1.0000,
                            "quantityFormat": "1 ks",
                            "sumQuantity": 1.00000000,
                            "sumQuantityFormat": "1 ks",
                            "unitCode": "ks",
                            "state": 3,
                            "stateFormat": "Plně",
                            "foundItems": [
                                {
                                    "id": 19,
                                    "barcode": "AM0520",
                                    "quantity": 1.0000,
                                    "ratio": 1.0000
                                }
                            ]
                        }
                    ]
                }
            ],
            "errors": []
        }

## Group Historie přihlášení / odhlášení
V systému **Label Printer** se ukládají jednotlivé pokusy o přihlášení / odhlášení (případně reset aktivity uživatele).

<a name="logonHistoryType"></a>
####Typ akce (type)
| Kód   | Typ       | Popis         |
|:------|-----------|---------------|
| `1`   | integer   | Přihlášení    |
| `2`   | integer   | Odhlášení     |
| `3`   | integer   | Reset         |

### API metody [/users/logonhistory]

#### Seznam přihlášení / odhlášení uživatele [POST /users/logonhistory/filter]

+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3
                
    + Body
    
            {
              "id": "interni id NEBO externi id NEBO login uživatele",
              "from": "2023-07-10 00:00",
              "to": "2023-07-10 23:59"
            }

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [
                {
                    "id": 31797,
                    "user": "Vojtěc Hernas",
                    "userExternalId": 1023,
                    "date": "2023-07-10 12:03:05",
                    "type": 1,
                    "typeFormat": "Přihlášení",
                    "succeeded": true
                },
                {
                    "id": 31798,
                    "user": "Vojtěc Hernas",
                    "userExternalId": 1023,
                    "date": "2023-07-10 12:08:05",
                    "type": 2,
                    "typeFormat": "Odhlášení",
                    "succeeded": true
                },
                {
                    "id": 31799,
                    "user": "Vojtěc Hernas",
                    "userExternalId": 1023,
                    "date": "2023-07-10 12:08:12",
                    "type": 1,
                    "typeFormat": "Přihlášení",
                    "succeeded": false
                },
                {
                    "id": 31800,
                    "user": "Vojtěc Hernas",
                    "userExternalId": 1023,
                    "date": "2023-07-10 14:40:19",
                    "type": 1,
                    "typeFormat": "Přihlášení",
                    "succeeded": true
                }
            ],
            "errors": []
        }

## Group Přepravci
**Label Printer** nabízí širokou škálu přepravců a jejich služeb (včetně doplňkových). Proto si snad z tohoto seznamu dokážete vybrat ty 
přepravce, které využíváte. Napojení na přepravce neustále rozšiřujeme, takže, i kdyby jste svého přepravce nenašli, tak je to nejspíš 
jen otázka času, než se do našeho seznamu dostane.

### API metody [/shippers]

#### Seznam přepravců [GET /shippers]
    
+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [
                {
                    "code": "CP",
                    "name": "Česká pošta, s.p.",
                    "phone": "+420 840 111 244",
                    "email": "info@cpost.cz",
                    "services": [
                        {
                            "code": "DR",
                            "name": "Do ruky"
                        },
                        {
                            "code": "BB",
                            "name": "Balík s udanou cenou do 10000,-Kč bez dobírky nebo s dobírkou"
                        },
                        {
                            "code": "VV",
                            "name": "Balík s udanou cenou nad 10000,-Kč bez dobírky nebo s dobírkou"
                        },
                        {
                            "code": "VL",
                            "name": "Cenné psaní"
                        },
                        {
                            "code": "RR",
                            "name": "Doporučená zásilka"
                        },
                        {
                            "code": "BA",
                            "name": "Doporučený balíček"
                        },
                        {
                            "code": "EE",
                            "name": "EMS"
                        },
                        {
                            "code": "CE",
                            "name": "Obchodní balík do ciziny"
                        },
                        {
                            "code": "BN",
                            "name": "Nadrozměrná zásilka"
                        },
                        {
                            "code": "DE",
                            "name": "Do ruky se službou Garantovaný čas dodání (pracovní dny a sobota)"
                        },
                        {
                            "code": "NP",
                            "name": "Na poštu"
                        },
                        {
                            "code": "BO",
                            "name": "Obchodní balík"
                        },
                        {
                            "code": "DV",
                            "name": "Do ruky pro vybrané podavatele"
                        },
                        {
                            "code": "NB",
                            "name": "Do balíkovny"
                        }
                    ]
                },
                {
                    "code": "DPD",
                    "name": "DPD",
                    "phone": "+420 225 373 373",
                    "email": "info@dpd.cz",
                    "services": [
                        {
                            "code": "CL",
                            "name": "DPD Classic"
                        },
                        {
                            "code": "PR",
                            "name": "DPD Private"
                        },
                        {
                            "code": "PS",
                            "name": "DPD Pickup"
                        },
                        {
                            "code": "PM",
                            "name": "DPD 18:00"
                        },
                        {
                            "code": "AM1",
                            "name": "DPD 10:00"
                        },
                        {
                            "code": "AM2",
                            "name": "DPD 12:00"
                        },
                        {
                            "code": "IE",
                            "name": "DPD Express"
                        },
                        {
                            "code": "PNEU",
                            "name": "DPD Pneu"
                        },
                        {
                            "code": "EV",
                            "name": "DPD Večer"
                        }
                    ]
                },
                {
                    "code": "GEIS",
                    "name": "GEIS",
                    "phone": "+420 951 277 777",
                    "email": "info@geis.cz",
                    "services": [
                        {
                            "code": "PV",
                            "name": "Parcel vnitrostátní (balíky)"
                        },
                        {
                            "code": "PM",
                            "name": "Parcel mezinárodní (balíky)"
                        },
                        {
                            "code": "CV",
                            "name": "Cargo vnitrostátní (palety)"
                        },
                        {
                            "code": "CM",
                            "name": "Cargo mezinárodní (palety)"
                        }
                    ]
                }
            ],
            "errors": []
        }
   
## Group Odběrná místa
Přes **Label Printer** `API` lze získat všechna odběrná místa všech přepvaců, které jsou uložena do databáze **Label Printer**. Stahování dat od přepravců je 
nastaveno buď automaticky skrz **Label Printer** nastavení anebo lze přes aplikaci **Label Printer** stáhnout ručně. `API` poskytuje odběrná místa pouze 
z lokální databáze a během požadavků nevolá služby přepravců (to dělá pouze aplikace **Label Printer** z výkonostních důvodů).

### API metody [/delivery-points]

#### Seznam všech odběrných míst [GET /delivery-points]
    
+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [
                {
                    "deliveryPointId": "74721-MATISOVA01",
                    "shipperCode": "GLS",
                    "serviceCode": "BP_PS",
                    "name": "CS PRIM",
                    "name2": null,
                    "street": "Štěpánkovická 3338",
                    "houseNumber": null,
                    "city": "Kravaře",
                    "zipCode": "74721",
                    "countryCode": "CZ",
                    "countryCode3Letters": "CZE",
                    "latitude": 49.9346,
                    "longitude": 18.0193,
                    "email": null,
                    "phone": "735758067",
                    "active": true
                }
            ],
            "errors": []
        }
        
#### Seznam odběrných míst přepravce [GET /delivery-points/{shipperCode}]
    
+ Parameters
    + shipperCode - Kód přepravce (např. cp, gls, dpd, zasilkovna atd.)
    
+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [
                {
                    "deliveryPointId": "74721-MATISOVA01",
                    "shipperCode": "GLS",
                    "serviceCode": "BP_PS",
                    "name": "CS PRIM",
                    "name2": null,
                    "street": "Štěpánkovická 3338",
                    "houseNumber": null,
                    "city": "Kravaře",
                    "zipCode": "74721",
                    "countryCode": "CZ",
                    "countryCode3Letters": "CZE",
                    "latitude": 49.9346,
                    "longitude": 18.0193,
                    "email": null,
                    "phone": "735758067",
                    "active": true
                }
            ],
            "errors": []
        }
        
#### Seznam odběrných míst dle filtru [POST /delivery-points/filter]
    
+ Request (application/json)
    + Headers
    
                Authorization: Bearer 4d060bc068f44909c1375c6cd4b773a3
                
    + Body
    
            {
                "shipperCode": "CP",
                "serviceCode": "NB",
                "deliveryPointId": "70200"
            }

+ Response 200 (application/json)

        {
            "code": 200,
            "data": [
                {
                    "deliveryPointId": "70200",
                    "shipperCode": "CP",
                    "serviceCode": "NB",
                    "name": "Ostrava 2",
                    "name2": null,
                    "street": "Wattova 1046/19",
                    "houseNumber": null,
                    "city": "Ostrava",
                    "zipCode": "70200",
                    "countryCode": "CZ",
                    "countryCode3Letters": "CZE",
                    "latitude": null,
                    "longitude": null,
                    "email": null,
                    "phone": null,
                    "active": true
                }
            ],
            "errors": []
        }
        
## Group Historie
Historie je možná součást vrácených dat u zásilek. Lze ji získat volitelným parametrem `includeHistory` nastaveným na hodnotu `true`. 
Další parametry týkající se historie, které lze zadat pro hledání zásilek jsou vysvětlené <a href="#shipment_search">zde</a>.

<a name="history_columns"></a>
#####Seznam používaných kódu pro parametr `column`
| `column`              | Význam                    |
|:----------------------|---------------------------|
| fk_country            | Země                      |
| fk_shipment_state     | Stav                      |
| companyOrName         | Společnost                |
| attention             | Osoba                     |
| address1              | Ulice                     |
| address2              | Doplnění adresy           |
| postalCode            | PSČ                       |
| city                  | Město                     |
| phone                 | Telefon                   |
| email                 | E-mail                    |
| isPaymentInAdvance    | Platba předem             |
| fk_service_type       | Přepravce a typ služby    |
| numberOfPackages      | Počet balíků              |
| weight                | Váha                      |
| reference1            | Variabilní symbol         |
| reference2            | Číslo objednávky          |
| descriptionOfGoods    | Popis                     |
| fk_currency           | Měna zásilky / dobírky    |
| price                 | Cena zásilky / dobírky    |
| bankAccount           | Číslo účtu                |
| barcode               | Čárový kód                |
| pcNamePrinted         | Tištěno na PC             |
